//
// Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
//
// timestamp removed
//
// BVI format method schedule info:
// schedule portalIfc_messageSize_size  CF ( portalIfc_messageSize_size,
// 					  portalIfc_indications_0_first,
// 					  portalIfc_indications_0_deq,
// 					  portalIfc_indications_0_notEmpty,
// 					  portalIfc_indications_1_first,
// 					  portalIfc_indications_1_deq,
// 					  portalIfc_indications_1_notEmpty,
// 					  portalIfc_indications_2_first,
// 					  portalIfc_indications_2_deq,
// 					  portalIfc_indications_2_notEmpty,
// 					  portalIfc_indications_3_first,
// 					  portalIfc_indications_3_deq,
// 					  portalIfc_indications_3_notEmpty,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel,
// 					  ifc_addrTrans,
// 					  ifc_setTileState,
// 					  ifc_stateDbg,
// 					  ifc_memoryTraffic );
//
// schedule portalIfc_indications_0_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_deq,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_deq,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_indications_3_first,
// 					     portalIfc_indications_3_deq,
// 					     portalIfc_indications_3_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_addrTrans,
// 					     ifc_setTileState,
// 					     ifc_stateDbg,
// 					     ifc_memoryTraffic );
// schedule portalIfc_indications_0_first  SB ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_indications_1_first,
// 					   portalIfc_indications_1_deq,
// 					   portalIfc_indications_1_notEmpty,
// 					   portalIfc_indications_2_first,
// 					   portalIfc_indications_2_deq,
// 					   portalIfc_indications_2_notEmpty,
// 					   portalIfc_indications_3_first,
// 					   portalIfc_indications_3_deq,
// 					   portalIfc_indications_3_notEmpty,
// 					   ifc_addrTrans,
// 					   ifc_setTileState,
// 					   ifc_stateDbg,
// 					   ifc_memoryTraffic );
// schedule portalIfc_indications_0_deq  C ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_deq,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_deq,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_indications_3_first,
// 						portalIfc_indications_3_deq,
// 						portalIfc_indications_3_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						ifc_setTileState,
// 						ifc_stateDbg,
// 						ifc_memoryTraffic );
// schedule portalIfc_indications_0_notEmpty  SB ( portalIfc_indications_0_deq,
// 						ifc_addrTrans );
//
// schedule portalIfc_indications_1_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_deq,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_deq,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_indications_3_first,
// 					     portalIfc_indications_3_deq,
// 					     portalIfc_indications_3_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_addrTrans,
// 					     ifc_setTileState,
// 					     ifc_stateDbg,
// 					     ifc_memoryTraffic );
// schedule portalIfc_indications_1_first  SB ( portalIfc_indications_1_deq );
//
// schedule portalIfc_indications_1_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_indications_0_first,
// 					   portalIfc_indications_0_deq,
// 					   portalIfc_indications_0_notEmpty,
// 					   portalIfc_indications_2_first,
// 					   portalIfc_indications_2_deq,
// 					   portalIfc_indications_2_notEmpty,
// 					   portalIfc_indications_3_first,
// 					   portalIfc_indications_3_deq,
// 					   portalIfc_indications_3_notEmpty,
// 					   ifc_addrTrans,
// 					   ifc_setTileState,
// 					   ifc_stateDbg,
// 					   ifc_memoryTraffic );
// schedule portalIfc_indications_1_deq  C ( portalIfc_indications_1_deq );
//
// schedule portalIfc_indications_1_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_deq,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_deq,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_indications_3_first,
// 						portalIfc_indications_3_deq,
// 						portalIfc_indications_3_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						ifc_addrTrans,
// 						ifc_stateDbg,
// 						ifc_memoryTraffic );
// schedule portalIfc_indications_1_notEmpty  SB ( portalIfc_indications_1_deq,
// 						ifc_setTileState );
//
// schedule portalIfc_indications_2_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_deq,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_deq,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_indications_3_first,
// 					     portalIfc_indications_3_deq,
// 					     portalIfc_indications_3_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_addrTrans,
// 					     ifc_setTileState,
// 					     ifc_stateDbg,
// 					     ifc_memoryTraffic );
// schedule portalIfc_indications_2_first  SB ( portalIfc_indications_2_deq );
//
// schedule portalIfc_indications_2_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_indications_0_first,
// 					   portalIfc_indications_0_deq,
// 					   portalIfc_indications_0_notEmpty,
// 					   portalIfc_indications_1_first,
// 					   portalIfc_indications_1_deq,
// 					   portalIfc_indications_1_notEmpty,
// 					   portalIfc_indications_3_first,
// 					   portalIfc_indications_3_deq,
// 					   portalIfc_indications_3_notEmpty,
// 					   ifc_addrTrans,
// 					   ifc_setTileState,
// 					   ifc_stateDbg,
// 					   ifc_memoryTraffic );
// schedule portalIfc_indications_2_deq  C ( portalIfc_indications_2_deq );
//
// schedule portalIfc_indications_2_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_deq,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_deq,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_indications_3_first,
// 						portalIfc_indications_3_deq,
// 						portalIfc_indications_3_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						ifc_addrTrans,
// 						ifc_setTileState,
// 						ifc_memoryTraffic );
// schedule portalIfc_indications_2_notEmpty  SB ( portalIfc_indications_2_deq,
// 						ifc_stateDbg );
//
// schedule portalIfc_indications_3_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_deq,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_deq,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_deq,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_indications_3_first,
// 					     portalIfc_indications_3_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_addrTrans,
// 					     ifc_setTileState,
// 					     ifc_stateDbg,
// 					     ifc_memoryTraffic );
// schedule portalIfc_indications_3_first  SB ( portalIfc_indications_3_deq );
//
// schedule portalIfc_indications_3_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_indications_0_first,
// 					   portalIfc_indications_0_deq,
// 					   portalIfc_indications_0_notEmpty,
// 					   portalIfc_indications_1_first,
// 					   portalIfc_indications_1_deq,
// 					   portalIfc_indications_1_notEmpty,
// 					   portalIfc_indications_2_first,
// 					   portalIfc_indications_2_deq,
// 					   portalIfc_indications_2_notEmpty,
// 					   ifc_addrTrans,
// 					   ifc_setTileState,
// 					   ifc_stateDbg,
// 					   ifc_memoryTraffic );
// schedule portalIfc_indications_3_deq  C ( portalIfc_indications_3_deq );
//
// schedule portalIfc_indications_3_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_deq,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_deq,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_deq,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_indications_3_first,
// 						portalIfc_indications_3_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						ifc_addrTrans,
// 						ifc_setTileState,
// 						ifc_stateDbg );
// schedule portalIfc_indications_3_notEmpty  SB ( portalIfc_indications_3_deq,
// 						ifc_memoryTraffic );
//
// schedule portalIfc_intr_status  CF ( portalIfc_messageSize_size,
// 				     portalIfc_indications_0_first,
// 				     portalIfc_indications_0_notEmpty,
// 				     portalIfc_indications_1_first,
// 				     portalIfc_indications_1_notEmpty,
// 				     portalIfc_indications_2_first,
// 				     portalIfc_indications_2_notEmpty,
// 				     portalIfc_indications_3_first,
// 				     portalIfc_indications_3_notEmpty,
// 				     portalIfc_intr_status,
// 				     portalIfc_intr_channel );
// schedule portalIfc_intr_status  SB ( portalIfc_indications_0_deq,
// 				     portalIfc_indications_1_deq,
// 				     portalIfc_indications_2_deq,
// 				     portalIfc_indications_3_deq,
// 				     ifc_addrTrans,
// 				     ifc_setTileState,
// 				     ifc_stateDbg,
// 				     ifc_memoryTraffic );
//
// schedule portalIfc_intr_channel  CF ( portalIfc_messageSize_size,
// 				      portalIfc_indications_0_first,
// 				      portalIfc_indications_0_notEmpty,
// 				      portalIfc_indications_1_first,
// 				      portalIfc_indications_1_notEmpty,
// 				      portalIfc_indications_2_first,
// 				      portalIfc_indications_2_notEmpty,
// 				      portalIfc_indications_3_first,
// 				      portalIfc_indications_3_notEmpty,
// 				      portalIfc_intr_status,
// 				      portalIfc_intr_channel );
// schedule portalIfc_intr_channel  SB ( portalIfc_indications_0_deq,
// 				      portalIfc_indications_1_deq,
// 				      portalIfc_indications_2_deq,
// 				      portalIfc_indications_3_deq,
// 				      ifc_addrTrans,
// 				      ifc_setTileState,
// 				      ifc_stateDbg,
// 				      ifc_memoryTraffic );
//
// schedule ifc_addrTrans  CF ( portalIfc_messageSize_size,
// 			     portalIfc_indications_0_first,
// 			     portalIfc_indications_0_deq,
// 			     portalIfc_indications_1_first,
// 			     portalIfc_indications_1_deq,
// 			     portalIfc_indications_1_notEmpty,
// 			     portalIfc_indications_2_first,
// 			     portalIfc_indications_2_deq,
// 			     portalIfc_indications_2_notEmpty,
// 			     portalIfc_indications_3_first,
// 			     portalIfc_indications_3_deq,
// 			     portalIfc_indications_3_notEmpty,
// 			     ifc_setTileState,
// 			     ifc_stateDbg,
// 			     ifc_memoryTraffic );
// schedule ifc_addrTrans  C ( ifc_addrTrans );
//
// schedule ifc_setTileState  CF ( portalIfc_messageSize_size,
// 				portalIfc_indications_0_first,
// 				portalIfc_indications_0_deq,
// 				portalIfc_indications_0_notEmpty,
// 				portalIfc_indications_1_first,
// 				portalIfc_indications_1_deq,
// 				portalIfc_indications_2_first,
// 				portalIfc_indications_2_deq,
// 				portalIfc_indications_2_notEmpty,
// 				portalIfc_indications_3_first,
// 				portalIfc_indications_3_deq,
// 				portalIfc_indications_3_notEmpty,
// 				ifc_addrTrans,
// 				ifc_stateDbg,
// 				ifc_memoryTraffic );
// schedule ifc_setTileState  C ( ifc_setTileState );
//
// schedule ifc_stateDbg  CF ( portalIfc_messageSize_size,
// 			    portalIfc_indications_0_first,
// 			    portalIfc_indications_0_deq,
// 			    portalIfc_indications_0_notEmpty,
// 			    portalIfc_indications_1_first,
// 			    portalIfc_indications_1_deq,
// 			    portalIfc_indications_1_notEmpty,
// 			    portalIfc_indications_2_first,
// 			    portalIfc_indications_2_deq,
// 			    portalIfc_indications_3_first,
// 			    portalIfc_indications_3_deq,
// 			    portalIfc_indications_3_notEmpty,
// 			    ifc_addrTrans,
// 			    ifc_setTileState,
// 			    ifc_memoryTraffic );
// schedule ifc_stateDbg  C ( ifc_stateDbg );
//
// schedule ifc_memoryTraffic  CF ( portalIfc_messageSize_size,
// 				 portalIfc_indications_0_first,
// 				 portalIfc_indications_0_deq,
// 				 portalIfc_indications_0_notEmpty,
// 				 portalIfc_indications_1_first,
// 				 portalIfc_indications_1_deq,
// 				 portalIfc_indications_1_notEmpty,
// 				 portalIfc_indications_2_first,
// 				 portalIfc_indications_2_deq,
// 				 portalIfc_indications_2_notEmpty,
// 				 portalIfc_indications_3_first,
// 				 portalIfc_indications_3_deq,
// 				 ifc_addrTrans,
// 				 ifc_setTileState,
// 				 ifc_stateDbg );
// schedule ifc_memoryTraffic  C ( ifc_memoryTraffic );
//
//
// Ports:
// Name                         I/O  size props
// portalIfc_messageSize_size     O    16
// RDY_portalIfc_messageSize_size  O     1 const
// portalIfc_indications_0_first  O    32 reg
// RDY_portalIfc_indications_0_first  O     1 reg
// RDY_portalIfc_indications_0_deq  O     1 reg
// portalIfc_indications_0_notEmpty  O     1 reg
// RDY_portalIfc_indications_0_notEmpty  O     1 const
// portalIfc_indications_1_first  O    32 reg
// RDY_portalIfc_indications_1_first  O     1 reg
// RDY_portalIfc_indications_1_deq  O     1 reg
// portalIfc_indications_1_notEmpty  O     1 reg
// RDY_portalIfc_indications_1_notEmpty  O     1 const
// portalIfc_indications_2_first  O    32 reg
// RDY_portalIfc_indications_2_first  O     1 reg
// RDY_portalIfc_indications_2_deq  O     1 reg
// portalIfc_indications_2_notEmpty  O     1 reg
// RDY_portalIfc_indications_2_notEmpty  O     1 const
// portalIfc_indications_3_first  O    32 reg
// RDY_portalIfc_indications_3_first  O     1 reg
// RDY_portalIfc_indications_3_deq  O     1 reg
// portalIfc_indications_3_notEmpty  O     1 reg
// RDY_portalIfc_indications_3_notEmpty  O     1 const
// portalIfc_intr_status          O     1
// RDY_portalIfc_intr_status      O     1 const
// portalIfc_intr_channel         O    32
// RDY_portalIfc_intr_channel     O     1 const
// RDY_ifc_addrTrans              O     1
// RDY_ifc_setTileState           O     1
// RDY_ifc_stateDbg               O     1
// RDY_ifc_memoryTraffic          O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// portalIfc_messageSize_size_methodNumber  I    16
// ifc_addrTrans_sglId            I    32
// ifc_addrTrans_offset           I    32
// ifc_setTileState_tc            I     4 reg
// ifc_stateDbg_rc                I     1 reg
// ifc_memoryTraffic_rc           I     1 reg
// EN_portalIfc_indications_0_deq  I     1
// EN_portalIfc_indications_1_deq  I     1
// EN_portalIfc_indications_2_deq  I     1
// EN_portalIfc_indications_3_deq  I     1
// EN_ifc_addrTrans               I     1
// EN_ifc_setTileState            I     1
// EN_ifc_stateDbg                I     1
// EN_ifc_memoryTraffic           I     1
//
// Combinational paths from inputs to outputs:
//   portalIfc_messageSize_size_methodNumber -> portalIfc_messageSize_size
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMemServerRequestOutput(CLK,
				RST_N,

				portalIfc_messageSize_size_methodNumber,
				portalIfc_messageSize_size,
				RDY_portalIfc_messageSize_size,

				portalIfc_indications_0_first,
				RDY_portalIfc_indications_0_first,

				EN_portalIfc_indications_0_deq,
				RDY_portalIfc_indications_0_deq,

				portalIfc_indications_0_notEmpty,
				RDY_portalIfc_indications_0_notEmpty,

				portalIfc_indications_1_first,
				RDY_portalIfc_indications_1_first,

				EN_portalIfc_indications_1_deq,
				RDY_portalIfc_indications_1_deq,

				portalIfc_indications_1_notEmpty,
				RDY_portalIfc_indications_1_notEmpty,

				portalIfc_indications_2_first,
				RDY_portalIfc_indications_2_first,

				EN_portalIfc_indications_2_deq,
				RDY_portalIfc_indications_2_deq,

				portalIfc_indications_2_notEmpty,
				RDY_portalIfc_indications_2_notEmpty,

				portalIfc_indications_3_first,
				RDY_portalIfc_indications_3_first,

				EN_portalIfc_indications_3_deq,
				RDY_portalIfc_indications_3_deq,

				portalIfc_indications_3_notEmpty,
				RDY_portalIfc_indications_3_notEmpty,

				portalIfc_intr_status,
				RDY_portalIfc_intr_status,

				portalIfc_intr_channel,
				RDY_portalIfc_intr_channel,

				ifc_addrTrans_sglId,
				ifc_addrTrans_offset,
				EN_ifc_addrTrans,
				RDY_ifc_addrTrans,

				ifc_setTileState_tc,
				EN_ifc_setTileState,
				RDY_ifc_setTileState,

				ifc_stateDbg_rc,
				EN_ifc_stateDbg,
				RDY_ifc_stateDbg,

				ifc_memoryTraffic_rc,
				EN_ifc_memoryTraffic,
				RDY_ifc_memoryTraffic);
  input  CLK;
  input  RST_N;

  // value method portalIfc_messageSize_size
  input  [15 : 0] portalIfc_messageSize_size_methodNumber;
  output [15 : 0] portalIfc_messageSize_size;
  output RDY_portalIfc_messageSize_size;

  // value method portalIfc_indications_0_first
  output [31 : 0] portalIfc_indications_0_first;
  output RDY_portalIfc_indications_0_first;

  // action method portalIfc_indications_0_deq
  input  EN_portalIfc_indications_0_deq;
  output RDY_portalIfc_indications_0_deq;

  // value method portalIfc_indications_0_notEmpty
  output portalIfc_indications_0_notEmpty;
  output RDY_portalIfc_indications_0_notEmpty;

  // value method portalIfc_indications_1_first
  output [31 : 0] portalIfc_indications_1_first;
  output RDY_portalIfc_indications_1_first;

  // action method portalIfc_indications_1_deq
  input  EN_portalIfc_indications_1_deq;
  output RDY_portalIfc_indications_1_deq;

  // value method portalIfc_indications_1_notEmpty
  output portalIfc_indications_1_notEmpty;
  output RDY_portalIfc_indications_1_notEmpty;

  // value method portalIfc_indications_2_first
  output [31 : 0] portalIfc_indications_2_first;
  output RDY_portalIfc_indications_2_first;

  // action method portalIfc_indications_2_deq
  input  EN_portalIfc_indications_2_deq;
  output RDY_portalIfc_indications_2_deq;

  // value method portalIfc_indications_2_notEmpty
  output portalIfc_indications_2_notEmpty;
  output RDY_portalIfc_indications_2_notEmpty;

  // value method portalIfc_indications_3_first
  output [31 : 0] portalIfc_indications_3_first;
  output RDY_portalIfc_indications_3_first;

  // action method portalIfc_indications_3_deq
  input  EN_portalIfc_indications_3_deq;
  output RDY_portalIfc_indications_3_deq;

  // value method portalIfc_indications_3_notEmpty
  output portalIfc_indications_3_notEmpty;
  output RDY_portalIfc_indications_3_notEmpty;

  // value method portalIfc_intr_status
  output portalIfc_intr_status;
  output RDY_portalIfc_intr_status;

  // value method portalIfc_intr_channel
  output [31 : 0] portalIfc_intr_channel;
  output RDY_portalIfc_intr_channel;

  // action method ifc_addrTrans
  input  [31 : 0] ifc_addrTrans_sglId;
  input  [31 : 0] ifc_addrTrans_offset;
  input  EN_ifc_addrTrans;
  output RDY_ifc_addrTrans;

  // action method ifc_setTileState
  input  [3 : 0] ifc_setTileState_tc;
  input  EN_ifc_setTileState;
  output RDY_ifc_setTileState;

  // action method ifc_stateDbg
  input  ifc_stateDbg_rc;
  input  EN_ifc_stateDbg;
  output RDY_ifc_stateDbg;

  // action method ifc_memoryTraffic
  input  ifc_memoryTraffic_rc;
  input  EN_ifc_memoryTraffic;
  output RDY_ifc_memoryTraffic;

  // signals for module outputs
  wire [31 : 0] portalIfc_indications_0_first,
		portalIfc_indications_1_first,
		portalIfc_indications_2_first,
		portalIfc_indications_3_first,
		portalIfc_intr_channel;
  wire [15 : 0] portalIfc_messageSize_size;
  wire RDY_ifc_addrTrans,
       RDY_ifc_memoryTraffic,
       RDY_ifc_setTileState,
       RDY_ifc_stateDbg,
       RDY_portalIfc_indications_0_deq,
       RDY_portalIfc_indications_0_first,
       RDY_portalIfc_indications_0_notEmpty,
       RDY_portalIfc_indications_1_deq,
       RDY_portalIfc_indications_1_first,
       RDY_portalIfc_indications_1_notEmpty,
       RDY_portalIfc_indications_2_deq,
       RDY_portalIfc_indications_2_first,
       RDY_portalIfc_indications_2_notEmpty,
       RDY_portalIfc_indications_3_deq,
       RDY_portalIfc_indications_3_first,
       RDY_portalIfc_indications_3_notEmpty,
       RDY_portalIfc_intr_channel,
       RDY_portalIfc_intr_status,
       RDY_portalIfc_messageSize_size,
       portalIfc_indications_0_notEmpty,
       portalIfc_indications_1_notEmpty,
       portalIfc_indications_2_notEmpty,
       portalIfc_indications_3_notEmpty,
       portalIfc_intr_status;

  // ports of submodule indicationPipes
  wire [63 : 0] indicationPipes_methods_addrTrans_enq_v;
  wire [31 : 0] indicationPipes_portalIfc_indications_0_first,
		indicationPipes_portalIfc_indications_1_first,
		indicationPipes_portalIfc_indications_2_first,
		indicationPipes_portalIfc_indications_3_first,
		indicationPipes_portalIfc_intr_channel;
  wire [15 : 0] indicationPipes_portalIfc_messageSize_size,
		indicationPipes_portalIfc_messageSize_size_methodNumber;
  wire [3 : 0] indicationPipes_methods_setTileState_enq_v;
  wire indicationPipes_EN_methods_addrTrans_enq,
       indicationPipes_EN_methods_memoryTraffic_enq,
       indicationPipes_EN_methods_setTileState_enq,
       indicationPipes_EN_methods_stateDbg_enq,
       indicationPipes_EN_portalIfc_indications_0_deq,
       indicationPipes_EN_portalIfc_indications_1_deq,
       indicationPipes_EN_portalIfc_indications_2_deq,
       indicationPipes_EN_portalIfc_indications_3_deq,
       indicationPipes_RDY_methods_addrTrans_enq,
       indicationPipes_RDY_methods_memoryTraffic_enq,
       indicationPipes_RDY_methods_setTileState_enq,
       indicationPipes_RDY_methods_stateDbg_enq,
       indicationPipes_RDY_portalIfc_indications_0_deq,
       indicationPipes_RDY_portalIfc_indications_0_first,
       indicationPipes_RDY_portalIfc_indications_1_deq,
       indicationPipes_RDY_portalIfc_indications_1_first,
       indicationPipes_RDY_portalIfc_indications_2_deq,
       indicationPipes_RDY_portalIfc_indications_2_first,
       indicationPipes_RDY_portalIfc_indications_3_deq,
       indicationPipes_RDY_portalIfc_indications_3_first,
       indicationPipes_methods_memoryTraffic_enq_v,
       indicationPipes_methods_stateDbg_enq_v,
       indicationPipes_portalIfc_indications_0_notEmpty,
       indicationPipes_portalIfc_indications_1_notEmpty,
       indicationPipes_portalIfc_indications_2_notEmpty,
       indicationPipes_portalIfc_indications_3_notEmpty,
       indicationPipes_portalIfc_intr_status;

  // value method portalIfc_messageSize_size
  assign portalIfc_messageSize_size =
	     indicationPipes_portalIfc_messageSize_size ;
  assign RDY_portalIfc_messageSize_size = 1'd1 ;

  // value method portalIfc_indications_0_first
  assign portalIfc_indications_0_first =
	     indicationPipes_portalIfc_indications_0_first ;
  assign RDY_portalIfc_indications_0_first =
	     indicationPipes_RDY_portalIfc_indications_0_first ;

  // action method portalIfc_indications_0_deq
  assign RDY_portalIfc_indications_0_deq =
	     indicationPipes_RDY_portalIfc_indications_0_deq ;

  // value method portalIfc_indications_0_notEmpty
  assign portalIfc_indications_0_notEmpty =
	     indicationPipes_portalIfc_indications_0_notEmpty ;
  assign RDY_portalIfc_indications_0_notEmpty = 1'd1 ;

  // value method portalIfc_indications_1_first
  assign portalIfc_indications_1_first =
	     indicationPipes_portalIfc_indications_1_first ;
  assign RDY_portalIfc_indications_1_first =
	     indicationPipes_RDY_portalIfc_indications_1_first ;

  // action method portalIfc_indications_1_deq
  assign RDY_portalIfc_indications_1_deq =
	     indicationPipes_RDY_portalIfc_indications_1_deq ;

  // value method portalIfc_indications_1_notEmpty
  assign portalIfc_indications_1_notEmpty =
	     indicationPipes_portalIfc_indications_1_notEmpty ;
  assign RDY_portalIfc_indications_1_notEmpty = 1'd1 ;

  // value method portalIfc_indications_2_first
  assign portalIfc_indications_2_first =
	     indicationPipes_portalIfc_indications_2_first ;
  assign RDY_portalIfc_indications_2_first =
	     indicationPipes_RDY_portalIfc_indications_2_first ;

  // action method portalIfc_indications_2_deq
  assign RDY_portalIfc_indications_2_deq =
	     indicationPipes_RDY_portalIfc_indications_2_deq ;

  // value method portalIfc_indications_2_notEmpty
  assign portalIfc_indications_2_notEmpty =
	     indicationPipes_portalIfc_indications_2_notEmpty ;
  assign RDY_portalIfc_indications_2_notEmpty = 1'd1 ;

  // value method portalIfc_indications_3_first
  assign portalIfc_indications_3_first =
	     indicationPipes_portalIfc_indications_3_first ;
  assign RDY_portalIfc_indications_3_first =
	     indicationPipes_RDY_portalIfc_indications_3_first ;

  // action method portalIfc_indications_3_deq
  assign RDY_portalIfc_indications_3_deq =
	     indicationPipes_RDY_portalIfc_indications_3_deq ;

  // value method portalIfc_indications_3_notEmpty
  assign portalIfc_indications_3_notEmpty =
	     indicationPipes_portalIfc_indications_3_notEmpty ;
  assign RDY_portalIfc_indications_3_notEmpty = 1'd1 ;

  // value method portalIfc_intr_status
  assign portalIfc_intr_status = indicationPipes_portalIfc_intr_status ;
  assign RDY_portalIfc_intr_status = 1'd1 ;

  // value method portalIfc_intr_channel
  assign portalIfc_intr_channel = indicationPipes_portalIfc_intr_channel ;
  assign RDY_portalIfc_intr_channel = 1'd1 ;

  // action method ifc_addrTrans
  assign RDY_ifc_addrTrans = indicationPipes_RDY_methods_addrTrans_enq ;

  // action method ifc_setTileState
  assign RDY_ifc_setTileState = indicationPipes_RDY_methods_setTileState_enq ;

  // action method ifc_stateDbg
  assign RDY_ifc_stateDbg = indicationPipes_RDY_methods_stateDbg_enq ;

  // action method ifc_memoryTraffic
  assign RDY_ifc_memoryTraffic =
	     indicationPipes_RDY_methods_memoryTraffic_enq ;

  // submodule indicationPipes
  mkMemServerRequestOutputPipes indicationPipes(.CLK(CLK),
						.RST_N(RST_N),
						.methods_addrTrans_enq_v(indicationPipes_methods_addrTrans_enq_v),
						.methods_memoryTraffic_enq_v(indicationPipes_methods_memoryTraffic_enq_v),
						.methods_setTileState_enq_v(indicationPipes_methods_setTileState_enq_v),
						.methods_stateDbg_enq_v(indicationPipes_methods_stateDbg_enq_v),
						.portalIfc_messageSize_size_methodNumber(indicationPipes_portalIfc_messageSize_size_methodNumber),
						.EN_methods_addrTrans_enq(indicationPipes_EN_methods_addrTrans_enq),
						.EN_methods_setTileState_enq(indicationPipes_EN_methods_setTileState_enq),
						.EN_methods_stateDbg_enq(indicationPipes_EN_methods_stateDbg_enq),
						.EN_methods_memoryTraffic_enq(indicationPipes_EN_methods_memoryTraffic_enq),
						.EN_portalIfc_indications_0_deq(indicationPipes_EN_portalIfc_indications_0_deq),
						.EN_portalIfc_indications_1_deq(indicationPipes_EN_portalIfc_indications_1_deq),
						.EN_portalIfc_indications_2_deq(indicationPipes_EN_portalIfc_indications_2_deq),
						.EN_portalIfc_indications_3_deq(indicationPipes_EN_portalIfc_indications_3_deq),
						.RDY_methods_addrTrans_enq(indicationPipes_RDY_methods_addrTrans_enq),
						.methods_addrTrans_notFull(),
						.RDY_methods_addrTrans_notFull(),
						.RDY_methods_setTileState_enq(indicationPipes_RDY_methods_setTileState_enq),
						.methods_setTileState_notFull(),
						.RDY_methods_setTileState_notFull(),
						.RDY_methods_stateDbg_enq(indicationPipes_RDY_methods_stateDbg_enq),
						.methods_stateDbg_notFull(),
						.RDY_methods_stateDbg_notFull(),
						.RDY_methods_memoryTraffic_enq(indicationPipes_RDY_methods_memoryTraffic_enq),
						.methods_memoryTraffic_notFull(),
						.RDY_methods_memoryTraffic_notFull(),
						.portalIfc_messageSize_size(indicationPipes_portalIfc_messageSize_size),
						.RDY_portalIfc_messageSize_size(),
						.portalIfc_indications_0_first(indicationPipes_portalIfc_indications_0_first),
						.RDY_portalIfc_indications_0_first(indicationPipes_RDY_portalIfc_indications_0_first),
						.RDY_portalIfc_indications_0_deq(indicationPipes_RDY_portalIfc_indications_0_deq),
						.portalIfc_indications_0_notEmpty(indicationPipes_portalIfc_indications_0_notEmpty),
						.RDY_portalIfc_indications_0_notEmpty(),
						.portalIfc_indications_1_first(indicationPipes_portalIfc_indications_1_first),
						.RDY_portalIfc_indications_1_first(indicationPipes_RDY_portalIfc_indications_1_first),
						.RDY_portalIfc_indications_1_deq(indicationPipes_RDY_portalIfc_indications_1_deq),
						.portalIfc_indications_1_notEmpty(indicationPipes_portalIfc_indications_1_notEmpty),
						.RDY_portalIfc_indications_1_notEmpty(),
						.portalIfc_indications_2_first(indicationPipes_portalIfc_indications_2_first),
						.RDY_portalIfc_indications_2_first(indicationPipes_RDY_portalIfc_indications_2_first),
						.RDY_portalIfc_indications_2_deq(indicationPipes_RDY_portalIfc_indications_2_deq),
						.portalIfc_indications_2_notEmpty(indicationPipes_portalIfc_indications_2_notEmpty),
						.RDY_portalIfc_indications_2_notEmpty(),
						.portalIfc_indications_3_first(indicationPipes_portalIfc_indications_3_first),
						.RDY_portalIfc_indications_3_first(indicationPipes_RDY_portalIfc_indications_3_first),
						.RDY_portalIfc_indications_3_deq(indicationPipes_RDY_portalIfc_indications_3_deq),
						.portalIfc_indications_3_notEmpty(indicationPipes_portalIfc_indications_3_notEmpty),
						.RDY_portalIfc_indications_3_notEmpty(),
						.portalIfc_intr_status(indicationPipes_portalIfc_intr_status),
						.RDY_portalIfc_intr_status(),
						.portalIfc_intr_channel(indicationPipes_portalIfc_intr_channel),
						.RDY_portalIfc_intr_channel());

  // submodule indicationPipes
  assign indicationPipes_methods_addrTrans_enq_v =
	     { ifc_addrTrans_sglId, ifc_addrTrans_offset } ;
  assign indicationPipes_methods_memoryTraffic_enq_v = ifc_memoryTraffic_rc ;
  assign indicationPipes_methods_setTileState_enq_v = ifc_setTileState_tc ;
  assign indicationPipes_methods_stateDbg_enq_v = ifc_stateDbg_rc ;
  assign indicationPipes_portalIfc_messageSize_size_methodNumber =
	     portalIfc_messageSize_size_methodNumber ;
  assign indicationPipes_EN_methods_addrTrans_enq = EN_ifc_addrTrans ;
  assign indicationPipes_EN_methods_setTileState_enq = EN_ifc_setTileState ;
  assign indicationPipes_EN_methods_stateDbg_enq = EN_ifc_stateDbg ;
  assign indicationPipes_EN_methods_memoryTraffic_enq = EN_ifc_memoryTraffic ;
  assign indicationPipes_EN_portalIfc_indications_0_deq =
	     EN_portalIfc_indications_0_deq ;
  assign indicationPipes_EN_portalIfc_indications_1_deq =
	     EN_portalIfc_indications_1_deq ;
  assign indicationPipes_EN_portalIfc_indications_2_deq =
	     EN_portalIfc_indications_2_deq ;
  assign indicationPipes_EN_portalIfc_indications_3_deq =
	     EN_portalIfc_indications_3_deq ;
endmodule  // mkMemServerRequestOutput

