//
// Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
//
// timestamp removed
//
// BVI format method schedule info:
// schedule methods_idResponse_enq  CF ( methods_configResp_enq,
// 				      methods_configResp_notFull,
// 				      methods_error_enq,
// 				      methods_error_notFull,
// 				      portalIfc_messageSize_size,
// 				      portalIfc_indications_0_first,
// 				      portalIfc_indications_0_deq,
// 				      portalIfc_indications_1_first,
// 				      portalIfc_indications_1_deq,
// 				      portalIfc_indications_1_notEmpty,
// 				      portalIfc_indications_2_first,
// 				      portalIfc_indications_2_deq,
// 				      portalIfc_indications_2_notEmpty );
// schedule methods_idResponse_enq  C ( methods_idResponse_enq );
//
// schedule methods_idResponse_notFull  CF ( methods_idResponse_notFull,
// 					  methods_configResp_enq,
// 					  methods_configResp_notFull,
// 					  methods_error_enq,
// 					  methods_error_notFull,
// 					  portalIfc_messageSize_size,
// 					  portalIfc_indications_0_first,
// 					  portalIfc_indications_0_notEmpty,
// 					  portalIfc_indications_1_first,
// 					  portalIfc_indications_1_deq,
// 					  portalIfc_indications_1_notEmpty,
// 					  portalIfc_indications_2_first,
// 					  portalIfc_indications_2_deq,
// 					  portalIfc_indications_2_notEmpty,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel );
// schedule methods_idResponse_notFull  SB ( methods_idResponse_enq,
// 					  portalIfc_indications_0_deq );
//
// schedule methods_configResp_enq  CF ( methods_idResponse_enq,
// 				      methods_idResponse_notFull,
// 				      methods_error_enq,
// 				      methods_error_notFull,
// 				      portalIfc_messageSize_size,
// 				      portalIfc_indications_0_first,
// 				      portalIfc_indications_0_deq,
// 				      portalIfc_indications_0_notEmpty,
// 				      portalIfc_indications_1_first,
// 				      portalIfc_indications_1_deq,
// 				      portalIfc_indications_2_first,
// 				      portalIfc_indications_2_deq,
// 				      portalIfc_indications_2_notEmpty );
// schedule methods_configResp_enq  C ( methods_configResp_enq );
//
// schedule methods_configResp_notFull  CF ( methods_idResponse_enq,
// 					  methods_idResponse_notFull,
// 					  methods_configResp_notFull,
// 					  methods_error_enq,
// 					  methods_error_notFull,
// 					  portalIfc_messageSize_size,
// 					  portalIfc_indications_0_first,
// 					  portalIfc_indications_0_deq,
// 					  portalIfc_indications_0_notEmpty,
// 					  portalIfc_indications_1_first,
// 					  portalIfc_indications_1_notEmpty,
// 					  portalIfc_indications_2_first,
// 					  portalIfc_indications_2_deq,
// 					  portalIfc_indications_2_notEmpty,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel );
// schedule methods_configResp_notFull  SB ( methods_configResp_enq,
// 					  portalIfc_indications_1_deq );
//
// schedule methods_error_enq  CF ( methods_idResponse_enq,
// 				 methods_idResponse_notFull,
// 				 methods_configResp_enq,
// 				 methods_configResp_notFull,
// 				 portalIfc_messageSize_size,
// 				 portalIfc_indications_0_first,
// 				 portalIfc_indications_0_deq,
// 				 portalIfc_indications_0_notEmpty,
// 				 portalIfc_indications_1_first,
// 				 portalIfc_indications_1_deq,
// 				 portalIfc_indications_1_notEmpty,
// 				 portalIfc_indications_2_first,
// 				 portalIfc_indications_2_deq );
// schedule methods_error_enq  C ( methods_error_enq );
//
// schedule methods_error_notFull  CF ( methods_idResponse_enq,
// 				     methods_idResponse_notFull,
// 				     methods_configResp_enq,
// 				     methods_configResp_notFull,
// 				     methods_error_notFull,
// 				     portalIfc_messageSize_size,
// 				     portalIfc_indications_0_first,
// 				     portalIfc_indications_0_deq,
// 				     portalIfc_indications_0_notEmpty,
// 				     portalIfc_indications_1_first,
// 				     portalIfc_indications_1_deq,
// 				     portalIfc_indications_1_notEmpty,
// 				     portalIfc_indications_2_first,
// 				     portalIfc_indications_2_notEmpty,
// 				     portalIfc_intr_status,
// 				     portalIfc_intr_channel );
// schedule methods_error_notFull  SB ( methods_error_enq,
// 				     portalIfc_indications_2_deq );
//
// schedule portalIfc_messageSize_size  CF ( methods_idResponse_enq,
// 					  methods_idResponse_notFull,
// 					  methods_configResp_enq,
// 					  methods_configResp_notFull,
// 					  methods_error_enq,
// 					  methods_error_notFull,
// 					  portalIfc_messageSize_size,
// 					  portalIfc_indications_0_first,
// 					  portalIfc_indications_0_deq,
// 					  portalIfc_indications_0_notEmpty,
// 					  portalIfc_indications_1_first,
// 					  portalIfc_indications_1_deq,
// 					  portalIfc_indications_1_notEmpty,
// 					  portalIfc_indications_2_first,
// 					  portalIfc_indications_2_deq,
// 					  portalIfc_indications_2_notEmpty,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel );
//
// schedule portalIfc_indications_0_first  CF ( methods_idResponse_enq,
// 					     methods_idResponse_notFull,
// 					     methods_configResp_enq,
// 					     methods_configResp_notFull,
// 					     methods_error_enq,
// 					     methods_error_notFull,
// 					     portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_deq,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_deq,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel );
// schedule portalIfc_indications_0_first  SB ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_deq  CF ( methods_idResponse_enq,
// 					   methods_configResp_enq,
// 					   methods_configResp_notFull,
// 					   methods_error_enq,
// 					   methods_error_notFull,
// 					   portalIfc_messageSize_size,
// 					   portalIfc_indications_1_first,
// 					   portalIfc_indications_1_deq,
// 					   portalIfc_indications_1_notEmpty,
// 					   portalIfc_indications_2_first,
// 					   portalIfc_indications_2_deq,
// 					   portalIfc_indications_2_notEmpty );
// schedule portalIfc_indications_0_deq  C ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_notEmpty  CF ( methods_idResponse_notFull,
// 						methods_configResp_enq,
// 						methods_configResp_notFull,
// 						methods_error_enq,
// 						methods_error_notFull,
// 						portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_deq,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_deq,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel );
// schedule portalIfc_indications_0_notEmpty  SB ( methods_idResponse_enq,
// 						portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_1_first  CF ( methods_idResponse_enq,
// 					     methods_idResponse_notFull,
// 					     methods_configResp_enq,
// 					     methods_configResp_notFull,
// 					     methods_error_enq,
// 					     methods_error_notFull,
// 					     portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_deq,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_deq,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel );
// schedule portalIfc_indications_1_first  SB ( portalIfc_indications_1_deq );
//
// schedule portalIfc_indications_1_deq  CF ( methods_idResponse_enq,
// 					   methods_idResponse_notFull,
// 					   methods_configResp_enq,
// 					   methods_error_enq,
// 					   methods_error_notFull,
// 					   portalIfc_messageSize_size,
// 					   portalIfc_indications_0_first,
// 					   portalIfc_indications_0_deq,
// 					   portalIfc_indications_0_notEmpty,
// 					   portalIfc_indications_2_first,
// 					   portalIfc_indications_2_deq,
// 					   portalIfc_indications_2_notEmpty );
// schedule portalIfc_indications_1_deq  C ( portalIfc_indications_1_deq );
//
// schedule portalIfc_indications_1_notEmpty  CF ( methods_idResponse_enq,
// 						methods_idResponse_notFull,
// 						methods_configResp_notFull,
// 						methods_error_enq,
// 						methods_error_notFull,
// 						portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_deq,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_deq,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel );
// schedule portalIfc_indications_1_notEmpty  SB ( methods_configResp_enq,
// 						portalIfc_indications_1_deq );
//
// schedule portalIfc_indications_2_first  CF ( methods_idResponse_enq,
// 					     methods_idResponse_notFull,
// 					     methods_configResp_enq,
// 					     methods_configResp_notFull,
// 					     methods_error_enq,
// 					     methods_error_notFull,
// 					     portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_deq,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_deq,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel );
// schedule portalIfc_indications_2_first  SB ( portalIfc_indications_2_deq );
//
// schedule portalIfc_indications_2_deq  CF ( methods_idResponse_enq,
// 					   methods_idResponse_notFull,
// 					   methods_configResp_enq,
// 					   methods_configResp_notFull,
// 					   methods_error_enq,
// 					   portalIfc_messageSize_size,
// 					   portalIfc_indications_0_first,
// 					   portalIfc_indications_0_deq,
// 					   portalIfc_indications_0_notEmpty,
// 					   portalIfc_indications_1_first,
// 					   portalIfc_indications_1_deq,
// 					   portalIfc_indications_1_notEmpty );
// schedule portalIfc_indications_2_deq  C ( portalIfc_indications_2_deq );
//
// schedule portalIfc_indications_2_notEmpty  CF ( methods_idResponse_enq,
// 						methods_idResponse_notFull,
// 						methods_configResp_enq,
// 						methods_configResp_notFull,
// 						methods_error_notFull,
// 						portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_deq,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_deq,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel );
// schedule portalIfc_indications_2_notEmpty  SB ( methods_error_enq,
// 						portalIfc_indications_2_deq );
//
// schedule portalIfc_intr_status  CF ( methods_idResponse_notFull,
// 				     methods_configResp_notFull,
// 				     methods_error_notFull,
// 				     portalIfc_messageSize_size,
// 				     portalIfc_indications_0_first,
// 				     portalIfc_indications_0_notEmpty,
// 				     portalIfc_indications_1_first,
// 				     portalIfc_indications_1_notEmpty,
// 				     portalIfc_indications_2_first,
// 				     portalIfc_indications_2_notEmpty,
// 				     portalIfc_intr_status,
// 				     portalIfc_intr_channel );
// schedule portalIfc_intr_status  SB ( methods_idResponse_enq,
// 				     methods_configResp_enq,
// 				     methods_error_enq,
// 				     portalIfc_indications_0_deq,
// 				     portalIfc_indications_1_deq,
// 				     portalIfc_indications_2_deq );
//
// schedule portalIfc_intr_channel  CF ( methods_idResponse_notFull,
// 				      methods_configResp_notFull,
// 				      methods_error_notFull,
// 				      portalIfc_messageSize_size,
// 				      portalIfc_indications_0_first,
// 				      portalIfc_indications_0_notEmpty,
// 				      portalIfc_indications_1_first,
// 				      portalIfc_indications_1_notEmpty,
// 				      portalIfc_indications_2_first,
// 				      portalIfc_indications_2_notEmpty,
// 				      portalIfc_intr_status,
// 				      portalIfc_intr_channel );
// schedule portalIfc_intr_channel  SB ( methods_idResponse_enq,
// 				      methods_configResp_enq,
// 				      methods_error_enq,
// 				      portalIfc_indications_0_deq,
// 				      portalIfc_indications_1_deq,
// 				      portalIfc_indications_2_deq );
//
//
// Ports:
// Name                         I/O  size props
// RDY_methods_idResponse_enq     O     1
// methods_idResponse_notFull     O     1
// RDY_methods_idResponse_notFull  O     1 const
// RDY_methods_configResp_enq     O     1
// methods_configResp_notFull     O     1
// RDY_methods_configResp_notFull  O     1 const
// RDY_methods_error_enq          O     1
// methods_error_notFull          O     1
// RDY_methods_error_notFull      O     1 const
// portalIfc_messageSize_size     O    16
// RDY_portalIfc_messageSize_size  O     1 const
// portalIfc_indications_0_first  O    32 reg
// RDY_portalIfc_indications_0_first  O     1 reg
// RDY_portalIfc_indications_0_deq  O     1 reg
// portalIfc_indications_0_notEmpty  O     1 reg
// RDY_portalIfc_indications_0_notEmpty  O     1 const
// portalIfc_indications_1_first  O    32 reg
// RDY_portalIfc_indications_1_first  O     1 reg
// RDY_portalIfc_indications_1_deq  O     1 reg
// portalIfc_indications_1_notEmpty  O     1 reg
// RDY_portalIfc_indications_1_notEmpty  O     1 const
// portalIfc_indications_2_first  O    32 reg
// RDY_portalIfc_indications_2_first  O     1 reg
// RDY_portalIfc_indications_2_deq  O     1 reg
// portalIfc_indications_2_notEmpty  O     1 reg
// RDY_portalIfc_indications_2_notEmpty  O     1 const
// portalIfc_intr_status          O     1
// RDY_portalIfc_intr_status      O     1 const
// portalIfc_intr_channel         O    32
// RDY_portalIfc_intr_channel     O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// methods_idResponse_enq_v       I    32 reg
// methods_configResp_enq_v       I    32 reg
// methods_error_enq_v            I   192
// portalIfc_messageSize_size_methodNumber  I    16
// EN_methods_idResponse_enq      I     1
// EN_methods_configResp_enq      I     1
// EN_methods_error_enq           I     1
// EN_portalIfc_indications_0_deq  I     1
// EN_portalIfc_indications_1_deq  I     1
// EN_portalIfc_indications_2_deq  I     1
//
// Combinational paths from inputs to outputs:
//   portalIfc_messageSize_size_methodNumber -> portalIfc_messageSize_size
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMMUIndicationOutputPipes(CLK,
				  RST_N,

				  methods_idResponse_enq_v,
				  EN_methods_idResponse_enq,
				  RDY_methods_idResponse_enq,

				  methods_idResponse_notFull,
				  RDY_methods_idResponse_notFull,

				  methods_configResp_enq_v,
				  EN_methods_configResp_enq,
				  RDY_methods_configResp_enq,

				  methods_configResp_notFull,
				  RDY_methods_configResp_notFull,

				  methods_error_enq_v,
				  EN_methods_error_enq,
				  RDY_methods_error_enq,

				  methods_error_notFull,
				  RDY_methods_error_notFull,

				  portalIfc_messageSize_size_methodNumber,
				  portalIfc_messageSize_size,
				  RDY_portalIfc_messageSize_size,

				  portalIfc_indications_0_first,
				  RDY_portalIfc_indications_0_first,

				  EN_portalIfc_indications_0_deq,
				  RDY_portalIfc_indications_0_deq,

				  portalIfc_indications_0_notEmpty,
				  RDY_portalIfc_indications_0_notEmpty,

				  portalIfc_indications_1_first,
				  RDY_portalIfc_indications_1_first,

				  EN_portalIfc_indications_1_deq,
				  RDY_portalIfc_indications_1_deq,

				  portalIfc_indications_1_notEmpty,
				  RDY_portalIfc_indications_1_notEmpty,

				  portalIfc_indications_2_first,
				  RDY_portalIfc_indications_2_first,

				  EN_portalIfc_indications_2_deq,
				  RDY_portalIfc_indications_2_deq,

				  portalIfc_indications_2_notEmpty,
				  RDY_portalIfc_indications_2_notEmpty,

				  portalIfc_intr_status,
				  RDY_portalIfc_intr_status,

				  portalIfc_intr_channel,
				  RDY_portalIfc_intr_channel);
  input  CLK;
  input  RST_N;

  // action method methods_idResponse_enq
  input  [31 : 0] methods_idResponse_enq_v;
  input  EN_methods_idResponse_enq;
  output RDY_methods_idResponse_enq;

  // value method methods_idResponse_notFull
  output methods_idResponse_notFull;
  output RDY_methods_idResponse_notFull;

  // action method methods_configResp_enq
  input  [31 : 0] methods_configResp_enq_v;
  input  EN_methods_configResp_enq;
  output RDY_methods_configResp_enq;

  // value method methods_configResp_notFull
  output methods_configResp_notFull;
  output RDY_methods_configResp_notFull;

  // action method methods_error_enq
  input  [191 : 0] methods_error_enq_v;
  input  EN_methods_error_enq;
  output RDY_methods_error_enq;

  // value method methods_error_notFull
  output methods_error_notFull;
  output RDY_methods_error_notFull;

  // value method portalIfc_messageSize_size
  input  [15 : 0] portalIfc_messageSize_size_methodNumber;
  output [15 : 0] portalIfc_messageSize_size;
  output RDY_portalIfc_messageSize_size;

  // value method portalIfc_indications_0_first
  output [31 : 0] portalIfc_indications_0_first;
  output RDY_portalIfc_indications_0_first;

  // action method portalIfc_indications_0_deq
  input  EN_portalIfc_indications_0_deq;
  output RDY_portalIfc_indications_0_deq;

  // value method portalIfc_indications_0_notEmpty
  output portalIfc_indications_0_notEmpty;
  output RDY_portalIfc_indications_0_notEmpty;

  // value method portalIfc_indications_1_first
  output [31 : 0] portalIfc_indications_1_first;
  output RDY_portalIfc_indications_1_first;

  // action method portalIfc_indications_1_deq
  input  EN_portalIfc_indications_1_deq;
  output RDY_portalIfc_indications_1_deq;

  // value method portalIfc_indications_1_notEmpty
  output portalIfc_indications_1_notEmpty;
  output RDY_portalIfc_indications_1_notEmpty;

  // value method portalIfc_indications_2_first
  output [31 : 0] portalIfc_indications_2_first;
  output RDY_portalIfc_indications_2_first;

  // action method portalIfc_indications_2_deq
  input  EN_portalIfc_indications_2_deq;
  output RDY_portalIfc_indications_2_deq;

  // value method portalIfc_indications_2_notEmpty
  output portalIfc_indications_2_notEmpty;
  output RDY_portalIfc_indications_2_notEmpty;

  // value method portalIfc_intr_status
  output portalIfc_intr_status;
  output RDY_portalIfc_intr_status;

  // value method portalIfc_intr_channel
  output [31 : 0] portalIfc_intr_channel;
  output RDY_portalIfc_intr_channel;

  // signals for module outputs
  reg [15 : 0] portalIfc_messageSize_size;
  wire [31 : 0] portalIfc_indications_0_first,
		portalIfc_indications_1_first,
		portalIfc_indications_2_first,
		portalIfc_intr_channel;
  wire RDY_methods_configResp_enq,
       RDY_methods_configResp_notFull,
       RDY_methods_error_enq,
       RDY_methods_error_notFull,
       RDY_methods_idResponse_enq,
       RDY_methods_idResponse_notFull,
       RDY_portalIfc_indications_0_deq,
       RDY_portalIfc_indications_0_first,
       RDY_portalIfc_indications_0_notEmpty,
       RDY_portalIfc_indications_1_deq,
       RDY_portalIfc_indications_1_first,
       RDY_portalIfc_indications_1_notEmpty,
       RDY_portalIfc_indications_2_deq,
       RDY_portalIfc_indications_2_first,
       RDY_portalIfc_indications_2_notEmpty,
       RDY_portalIfc_intr_channel,
       RDY_portalIfc_intr_status,
       RDY_portalIfc_messageSize_size,
       methods_configResp_notFull,
       methods_error_notFull,
       methods_idResponse_notFull,
       portalIfc_indications_0_notEmpty,
       portalIfc_indications_1_notEmpty,
       portalIfc_indications_2_notEmpty,
       portalIfc_intr_status;

  // register configResp_responseAdapter_bits
  reg [31 : 0] configResp_responseAdapter_bits;
  wire [31 : 0] configResp_responseAdapter_bits_D_IN;
  wire configResp_responseAdapter_bits_EN;

  // register configResp_responseAdapter_notEmptyReg
  reg configResp_responseAdapter_notEmptyReg;
  wire configResp_responseAdapter_notEmptyReg_D_IN,
       configResp_responseAdapter_notEmptyReg_EN;

  // register configResp_responseAdapter_shift
  reg [5 : 0] configResp_responseAdapter_shift;
  wire [5 : 0] configResp_responseAdapter_shift_D_IN;
  wire configResp_responseAdapter_shift_EN;

  // register error_responseAdapter_bits
  reg [191 : 0] error_responseAdapter_bits;
  wire [191 : 0] error_responseAdapter_bits_D_IN;
  wire error_responseAdapter_bits_EN;

  // register error_responseAdapter_count
  reg [2 : 0] error_responseAdapter_count;
  wire [2 : 0] error_responseAdapter_count_D_IN;
  wire error_responseAdapter_count_EN;

  // register error_responseAdapter_notEmptyReg
  reg error_responseAdapter_notEmptyReg;
  wire error_responseAdapter_notEmptyReg_D_IN,
       error_responseAdapter_notEmptyReg_EN;

  // register error_responseAdapter_shift
  reg [8 : 0] error_responseAdapter_shift;
  wire [8 : 0] error_responseAdapter_shift_D_IN;
  wire error_responseAdapter_shift_EN;

  // register idResponse_responseAdapter_bits
  reg [31 : 0] idResponse_responseAdapter_bits;
  wire [31 : 0] idResponse_responseAdapter_bits_D_IN;
  wire idResponse_responseAdapter_bits_EN;

  // register idResponse_responseAdapter_notEmptyReg
  reg idResponse_responseAdapter_notEmptyReg;
  wire idResponse_responseAdapter_notEmptyReg_D_IN,
       idResponse_responseAdapter_notEmptyReg_EN;

  // register idResponse_responseAdapter_shift
  reg [5 : 0] idResponse_responseAdapter_shift;
  wire [5 : 0] idResponse_responseAdapter_shift_D_IN;
  wire idResponse_responseAdapter_shift_EN;

  // inputs to muxes for submodule ports
  wire [191 : 0] MUX_error_responseAdapter_bits_write_1__VAL_1;
  wire MUX_error_responseAdapter_bits_write_1__SEL_1,
       MUX_error_responseAdapter_notEmptyReg_write_1__SEL_1;

  // remaining internal signals
  wire [2 : 0] x__h1094;

  // action method methods_idResponse_enq
  assign RDY_methods_idResponse_enq =
	     !idResponse_responseAdapter_notEmptyReg ;

  // value method methods_idResponse_notFull
  assign methods_idResponse_notFull =
	     !idResponse_responseAdapter_notEmptyReg ;
  assign RDY_methods_idResponse_notFull = 1'd1 ;

  // action method methods_configResp_enq
  assign RDY_methods_configResp_enq =
	     !configResp_responseAdapter_notEmptyReg ;

  // value method methods_configResp_notFull
  assign methods_configResp_notFull =
	     !configResp_responseAdapter_notEmptyReg ;
  assign RDY_methods_configResp_notFull = 1'd1 ;

  // action method methods_error_enq
  assign RDY_methods_error_enq = !error_responseAdapter_notEmptyReg ;

  // value method methods_error_notFull
  assign methods_error_notFull = !error_responseAdapter_notEmptyReg ;
  assign RDY_methods_error_notFull = 1'd1 ;

  // value method portalIfc_messageSize_size
  always@(portalIfc_messageSize_size_methodNumber)
  begin
    case (portalIfc_messageSize_size_methodNumber)
      16'd0, 16'd1: portalIfc_messageSize_size = 16'd32;
      default: portalIfc_messageSize_size = 16'd192;
    endcase
  end
  assign RDY_portalIfc_messageSize_size = 1'd1 ;

  // value method portalIfc_indications_0_first
  assign portalIfc_indications_0_first = idResponse_responseAdapter_bits ;
  assign RDY_portalIfc_indications_0_first =
	     idResponse_responseAdapter_notEmptyReg ;

  // action method portalIfc_indications_0_deq
  assign RDY_portalIfc_indications_0_deq =
	     idResponse_responseAdapter_notEmptyReg ;

  // value method portalIfc_indications_0_notEmpty
  assign portalIfc_indications_0_notEmpty =
	     idResponse_responseAdapter_notEmptyReg ;
  assign RDY_portalIfc_indications_0_notEmpty = 1'd1 ;

  // value method portalIfc_indications_1_first
  assign portalIfc_indications_1_first = configResp_responseAdapter_bits ;
  assign RDY_portalIfc_indications_1_first =
	     configResp_responseAdapter_notEmptyReg ;

  // action method portalIfc_indications_1_deq
  assign RDY_portalIfc_indications_1_deq =
	     configResp_responseAdapter_notEmptyReg ;

  // value method portalIfc_indications_1_notEmpty
  assign portalIfc_indications_1_notEmpty =
	     configResp_responseAdapter_notEmptyReg ;
  assign RDY_portalIfc_indications_1_notEmpty = 1'd1 ;

  // value method portalIfc_indications_2_first
  assign portalIfc_indications_2_first = error_responseAdapter_bits[191:160] ;
  assign RDY_portalIfc_indications_2_first =
	     error_responseAdapter_notEmptyReg ;

  // action method portalIfc_indications_2_deq
  assign RDY_portalIfc_indications_2_deq = error_responseAdapter_notEmptyReg ;

  // value method portalIfc_indications_2_notEmpty
  assign portalIfc_indications_2_notEmpty =
	     error_responseAdapter_notEmptyReg ;
  assign RDY_portalIfc_indications_2_notEmpty = 1'd1 ;

  // value method portalIfc_intr_status
  assign portalIfc_intr_status =
	     idResponse_responseAdapter_notEmptyReg ||
	     configResp_responseAdapter_notEmptyReg ||
	     error_responseAdapter_notEmptyReg ;
  assign RDY_portalIfc_intr_status = 1'd1 ;

  // value method portalIfc_intr_channel
  assign portalIfc_intr_channel =
	     idResponse_responseAdapter_notEmptyReg ?
	       32'd0 :
	       (configResp_responseAdapter_notEmptyReg ?
		  32'd1 :
		  (error_responseAdapter_notEmptyReg ?
		     32'd2 :
		     32'hFFFFFFFF)) ;
  assign RDY_portalIfc_intr_channel = 1'd1 ;

  // inputs to muxes for submodule ports
  assign MUX_error_responseAdapter_bits_write_1__SEL_1 =
	     EN_portalIfc_indications_2_deq &&
	     error_responseAdapter_count != 3'd5 ;
  assign MUX_error_responseAdapter_notEmptyReg_write_1__SEL_1 =
	     EN_portalIfc_indications_2_deq &&
	     error_responseAdapter_count == 3'd5 ;
  assign MUX_error_responseAdapter_bits_write_1__VAL_1 =
	     { error_responseAdapter_bits[159:0], 32'd0 } ;

  // register configResp_responseAdapter_bits
  assign configResp_responseAdapter_bits_D_IN = methods_configResp_enq_v ;
  assign configResp_responseAdapter_bits_EN = EN_methods_configResp_enq ;

  // register configResp_responseAdapter_notEmptyReg
  assign configResp_responseAdapter_notEmptyReg_D_IN =
	     !EN_portalIfc_indications_1_deq ;
  assign configResp_responseAdapter_notEmptyReg_EN =
	     EN_portalIfc_indications_1_deq || EN_methods_configResp_enq ;

  // register configResp_responseAdapter_shift
  assign configResp_responseAdapter_shift_D_IN = 6'h0 ;
  assign configResp_responseAdapter_shift_EN = 1'b0 ;

  // register error_responseAdapter_bits
  assign error_responseAdapter_bits_D_IN =
	     MUX_error_responseAdapter_bits_write_1__SEL_1 ?
	       MUX_error_responseAdapter_bits_write_1__VAL_1 :
	       methods_error_enq_v ;
  assign error_responseAdapter_bits_EN =
	     EN_portalIfc_indications_2_deq &&
	     error_responseAdapter_count != 3'd5 ||
	     EN_methods_error_enq ;

  // register error_responseAdapter_count
  assign error_responseAdapter_count_D_IN =
	     (error_responseAdapter_count == 3'd5) ? 3'd0 : x__h1094 ;
  assign error_responseAdapter_count_EN = EN_portalIfc_indications_2_deq ;

  // register error_responseAdapter_notEmptyReg
  assign error_responseAdapter_notEmptyReg_D_IN =
	     !MUX_error_responseAdapter_notEmptyReg_write_1__SEL_1 ;
  assign error_responseAdapter_notEmptyReg_EN =
	     EN_portalIfc_indications_2_deq &&
	     error_responseAdapter_count == 3'd5 ||
	     EN_methods_error_enq ;

  // register error_responseAdapter_shift
  assign error_responseAdapter_shift_D_IN =
	     error_responseAdapter_shift + 9'd32 ;
  assign error_responseAdapter_shift_EN =
	     MUX_error_responseAdapter_bits_write_1__SEL_1 ;

  // register idResponse_responseAdapter_bits
  assign idResponse_responseAdapter_bits_D_IN = methods_idResponse_enq_v ;
  assign idResponse_responseAdapter_bits_EN = EN_methods_idResponse_enq ;

  // register idResponse_responseAdapter_notEmptyReg
  assign idResponse_responseAdapter_notEmptyReg_D_IN =
	     !EN_portalIfc_indications_0_deq ;
  assign idResponse_responseAdapter_notEmptyReg_EN =
	     EN_portalIfc_indications_0_deq || EN_methods_idResponse_enq ;

  // register idResponse_responseAdapter_shift
  assign idResponse_responseAdapter_shift_D_IN = 6'h0 ;
  assign idResponse_responseAdapter_shift_EN = 1'b0 ;

  // remaining internal signals
  assign x__h1094 = error_responseAdapter_count + 3'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        configResp_responseAdapter_bits <= `BSV_ASSIGNMENT_DELAY 32'd0;
	configResp_responseAdapter_notEmptyReg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	configResp_responseAdapter_shift <= `BSV_ASSIGNMENT_DELAY 6'd0;
	error_responseAdapter_bits <= `BSV_ASSIGNMENT_DELAY 192'd0;
	error_responseAdapter_count <= `BSV_ASSIGNMENT_DELAY 3'd0;
	error_responseAdapter_notEmptyReg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	error_responseAdapter_shift <= `BSV_ASSIGNMENT_DELAY 9'd0;
	idResponse_responseAdapter_bits <= `BSV_ASSIGNMENT_DELAY 32'd0;
	idResponse_responseAdapter_notEmptyReg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	idResponse_responseAdapter_shift <= `BSV_ASSIGNMENT_DELAY 6'd0;
      end
    else
      begin
        if (configResp_responseAdapter_bits_EN)
	  configResp_responseAdapter_bits <= `BSV_ASSIGNMENT_DELAY
	      configResp_responseAdapter_bits_D_IN;
	if (configResp_responseAdapter_notEmptyReg_EN)
	  configResp_responseAdapter_notEmptyReg <= `BSV_ASSIGNMENT_DELAY
	      configResp_responseAdapter_notEmptyReg_D_IN;
	if (configResp_responseAdapter_shift_EN)
	  configResp_responseAdapter_shift <= `BSV_ASSIGNMENT_DELAY
	      configResp_responseAdapter_shift_D_IN;
	if (error_responseAdapter_bits_EN)
	  error_responseAdapter_bits <= `BSV_ASSIGNMENT_DELAY
	      error_responseAdapter_bits_D_IN;
	if (error_responseAdapter_count_EN)
	  error_responseAdapter_count <= `BSV_ASSIGNMENT_DELAY
	      error_responseAdapter_count_D_IN;
	if (error_responseAdapter_notEmptyReg_EN)
	  error_responseAdapter_notEmptyReg <= `BSV_ASSIGNMENT_DELAY
	      error_responseAdapter_notEmptyReg_D_IN;
	if (error_responseAdapter_shift_EN)
	  error_responseAdapter_shift <= `BSV_ASSIGNMENT_DELAY
	      error_responseAdapter_shift_D_IN;
	if (idResponse_responseAdapter_bits_EN)
	  idResponse_responseAdapter_bits <= `BSV_ASSIGNMENT_DELAY
	      idResponse_responseAdapter_bits_D_IN;
	if (idResponse_responseAdapter_notEmptyReg_EN)
	  idResponse_responseAdapter_notEmptyReg <= `BSV_ASSIGNMENT_DELAY
	      idResponse_responseAdapter_notEmptyReg_D_IN;
	if (idResponse_responseAdapter_shift_EN)
	  idResponse_responseAdapter_shift <= `BSV_ASSIGNMENT_DELAY
	      idResponse_responseAdapter_shift_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    configResp_responseAdapter_bits = 32'hAAAAAAAA;
    configResp_responseAdapter_notEmptyReg = 1'h0;
    configResp_responseAdapter_shift = 6'h2A;
    error_responseAdapter_bits =
	192'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    error_responseAdapter_count = 3'h2;
    error_responseAdapter_notEmptyReg = 1'h0;
    error_responseAdapter_shift = 9'h0AA;
    idResponse_responseAdapter_bits = 32'hAAAAAAAA;
    idResponse_responseAdapter_notEmptyReg = 1'h0;
    idResponse_responseAdapter_shift = 6'h2A;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkMMUIndicationOutputPipes

