//
// Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
//
// timestamp removed
//
// BVI format method schedule info:
// schedule portalIfc_messageSize_size  CF ( portalIfc_messageSize_size,
// 					  portalIfc_requests_0_enq,
// 					  portalIfc_requests_0_notFull,
// 					  portalIfc_requests_1_enq,
// 					  portalIfc_requests_1_notFull,
// 					  portalIfc_requests_2_enq,
// 					  portalIfc_requests_2_notFull,
// 					  portalIfc_requests_3_enq,
// 					  portalIfc_requests_3_notFull,
// 					  portalIfc_requests_4_enq,
// 					  portalIfc_requests_4_notFull,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel,
// 					  pipes_sglist_PipeOut_first,
// 					  pipes_sglist_PipeOut_deq,
// 					  pipes_sglist_PipeOut_notEmpty,
// 					  pipes_region_PipeOut_first,
// 					  pipes_region_PipeOut_deq,
// 					  pipes_region_PipeOut_notEmpty,
// 					  pipes_idRequest_PipeOut_first,
// 					  pipes_idRequest_PipeOut_deq,
// 					  pipes_idRequest_PipeOut_notEmpty,
// 					  pipes_idReturn_PipeOut_first,
// 					  pipes_idReturn_PipeOut_deq,
// 					  pipes_idReturn_PipeOut_notEmpty,
// 					  pipes_setInterface_PipeOut_first,
// 					  pipes_setInterface_PipeOut_deq,
// 					  pipes_setInterface_PipeOut_notEmpty );
//
// schedule portalIfc_requests_0_enq  CF ( portalIfc_messageSize_size,
// 					portalIfc_requests_1_enq,
// 					portalIfc_requests_1_notFull,
// 					portalIfc_requests_2_enq,
// 					portalIfc_requests_2_notFull,
// 					portalIfc_requests_3_enq,
// 					portalIfc_requests_3_notFull,
// 					portalIfc_requests_4_enq,
// 					portalIfc_requests_4_notFull,
// 					portalIfc_intr_status,
// 					portalIfc_intr_channel,
// 					pipes_sglist_PipeOut_first,
// 					pipes_region_PipeOut_first,
// 					pipes_region_PipeOut_deq,
// 					pipes_region_PipeOut_notEmpty,
// 					pipes_idRequest_PipeOut_first,
// 					pipes_idRequest_PipeOut_deq,
// 					pipes_idRequest_PipeOut_notEmpty,
// 					pipes_idReturn_PipeOut_first,
// 					pipes_idReturn_PipeOut_deq,
// 					pipes_idReturn_PipeOut_notEmpty,
// 					pipes_setInterface_PipeOut_first,
// 					pipes_setInterface_PipeOut_deq,
// 					pipes_setInterface_PipeOut_notEmpty );
// schedule portalIfc_requests_0_enq  SB ( pipes_sglist_PipeOut_deq );
// schedule portalIfc_requests_0_enq  C ( portalIfc_requests_0_enq );
//
// schedule portalIfc_requests_0_notFull  CF ( portalIfc_messageSize_size,
// 					    portalIfc_requests_0_notFull,
// 					    portalIfc_requests_1_enq,
// 					    portalIfc_requests_1_notFull,
// 					    portalIfc_requests_2_enq,
// 					    portalIfc_requests_2_notFull,
// 					    portalIfc_requests_3_enq,
// 					    portalIfc_requests_3_notFull,
// 					    portalIfc_requests_4_enq,
// 					    portalIfc_requests_4_notFull,
// 					    portalIfc_intr_status,
// 					    portalIfc_intr_channel,
// 					    pipes_sglist_PipeOut_first,
// 					    pipes_sglist_PipeOut_notEmpty,
// 					    pipes_region_PipeOut_first,
// 					    pipes_region_PipeOut_deq,
// 					    pipes_region_PipeOut_notEmpty,
// 					    pipes_idRequest_PipeOut_first,
// 					    pipes_idRequest_PipeOut_deq,
// 					    pipes_idRequest_PipeOut_notEmpty,
// 					    pipes_idReturn_PipeOut_first,
// 					    pipes_idReturn_PipeOut_deq,
// 					    pipes_idReturn_PipeOut_notEmpty,
// 					    pipes_setInterface_PipeOut_first,
// 					    pipes_setInterface_PipeOut_deq,
// 					    pipes_setInterface_PipeOut_notEmpty );
// schedule portalIfc_requests_0_notFull  SB ( portalIfc_requests_0_enq,
// 					    pipes_sglist_PipeOut_deq );
//
// schedule portalIfc_requests_1_enq  CF ( portalIfc_messageSize_size,
// 					portalIfc_requests_0_enq,
// 					portalIfc_requests_0_notFull,
// 					portalIfc_requests_2_enq,
// 					portalIfc_requests_2_notFull,
// 					portalIfc_requests_3_enq,
// 					portalIfc_requests_3_notFull,
// 					portalIfc_requests_4_enq,
// 					portalIfc_requests_4_notFull,
// 					portalIfc_intr_status,
// 					portalIfc_intr_channel,
// 					pipes_sglist_PipeOut_first,
// 					pipes_sglist_PipeOut_deq,
// 					pipes_sglist_PipeOut_notEmpty,
// 					pipes_region_PipeOut_first,
// 					pipes_idRequest_PipeOut_first,
// 					pipes_idRequest_PipeOut_deq,
// 					pipes_idRequest_PipeOut_notEmpty,
// 					pipes_idReturn_PipeOut_first,
// 					pipes_idReturn_PipeOut_deq,
// 					pipes_idReturn_PipeOut_notEmpty,
// 					pipes_setInterface_PipeOut_first,
// 					pipes_setInterface_PipeOut_deq,
// 					pipes_setInterface_PipeOut_notEmpty );
// schedule portalIfc_requests_1_enq  SB ( pipes_region_PipeOut_deq );
// schedule portalIfc_requests_1_enq  C ( portalIfc_requests_1_enq );
//
// schedule portalIfc_requests_1_notFull  CF ( portalIfc_messageSize_size,
// 					    portalIfc_requests_0_enq,
// 					    portalIfc_requests_0_notFull,
// 					    portalIfc_requests_1_notFull,
// 					    portalIfc_requests_2_enq,
// 					    portalIfc_requests_2_notFull,
// 					    portalIfc_requests_3_enq,
// 					    portalIfc_requests_3_notFull,
// 					    portalIfc_requests_4_enq,
// 					    portalIfc_requests_4_notFull,
// 					    portalIfc_intr_status,
// 					    portalIfc_intr_channel,
// 					    pipes_sglist_PipeOut_first,
// 					    pipes_sglist_PipeOut_deq,
// 					    pipes_sglist_PipeOut_notEmpty,
// 					    pipes_region_PipeOut_first,
// 					    pipes_region_PipeOut_notEmpty,
// 					    pipes_idRequest_PipeOut_first,
// 					    pipes_idRequest_PipeOut_deq,
// 					    pipes_idRequest_PipeOut_notEmpty,
// 					    pipes_idReturn_PipeOut_first,
// 					    pipes_idReturn_PipeOut_deq,
// 					    pipes_idReturn_PipeOut_notEmpty,
// 					    pipes_setInterface_PipeOut_first,
// 					    pipes_setInterface_PipeOut_deq,
// 					    pipes_setInterface_PipeOut_notEmpty );
// schedule portalIfc_requests_1_notFull  SB ( portalIfc_requests_1_enq,
// 					    pipes_region_PipeOut_deq );
//
// schedule portalIfc_requests_2_enq  CF ( portalIfc_messageSize_size,
// 					portalIfc_requests_0_enq,
// 					portalIfc_requests_0_notFull,
// 					portalIfc_requests_1_enq,
// 					portalIfc_requests_1_notFull,
// 					portalIfc_requests_3_enq,
// 					portalIfc_requests_3_notFull,
// 					portalIfc_requests_4_enq,
// 					portalIfc_requests_4_notFull,
// 					portalIfc_intr_status,
// 					portalIfc_intr_channel,
// 					pipes_sglist_PipeOut_first,
// 					pipes_sglist_PipeOut_deq,
// 					pipes_sglist_PipeOut_notEmpty,
// 					pipes_region_PipeOut_first,
// 					pipes_region_PipeOut_deq,
// 					pipes_region_PipeOut_notEmpty,
// 					pipes_idRequest_PipeOut_first,
// 					pipes_idReturn_PipeOut_first,
// 					pipes_idReturn_PipeOut_deq,
// 					pipes_idReturn_PipeOut_notEmpty,
// 					pipes_setInterface_PipeOut_first,
// 					pipes_setInterface_PipeOut_deq,
// 					pipes_setInterface_PipeOut_notEmpty );
// schedule portalIfc_requests_2_enq  SB ( pipes_idRequest_PipeOut_deq );
// schedule portalIfc_requests_2_enq  C ( portalIfc_requests_2_enq );
//
// schedule portalIfc_requests_2_notFull  CF ( portalIfc_messageSize_size,
// 					    portalIfc_requests_0_enq,
// 					    portalIfc_requests_0_notFull,
// 					    portalIfc_requests_1_enq,
// 					    portalIfc_requests_1_notFull,
// 					    portalIfc_requests_2_notFull,
// 					    portalIfc_requests_3_enq,
// 					    portalIfc_requests_3_notFull,
// 					    portalIfc_requests_4_enq,
// 					    portalIfc_requests_4_notFull,
// 					    portalIfc_intr_status,
// 					    portalIfc_intr_channel,
// 					    pipes_sglist_PipeOut_first,
// 					    pipes_sglist_PipeOut_deq,
// 					    pipes_sglist_PipeOut_notEmpty,
// 					    pipes_region_PipeOut_first,
// 					    pipes_region_PipeOut_deq,
// 					    pipes_region_PipeOut_notEmpty,
// 					    pipes_idRequest_PipeOut_first,
// 					    pipes_idRequest_PipeOut_notEmpty,
// 					    pipes_idReturn_PipeOut_first,
// 					    pipes_idReturn_PipeOut_deq,
// 					    pipes_idReturn_PipeOut_notEmpty,
// 					    pipes_setInterface_PipeOut_first,
// 					    pipes_setInterface_PipeOut_deq,
// 					    pipes_setInterface_PipeOut_notEmpty );
// schedule portalIfc_requests_2_notFull  SB ( portalIfc_requests_2_enq,
// 					    pipes_idRequest_PipeOut_deq );
//
// schedule portalIfc_requests_3_enq  CF ( portalIfc_messageSize_size,
// 					portalIfc_requests_0_enq,
// 					portalIfc_requests_0_notFull,
// 					portalIfc_requests_1_enq,
// 					portalIfc_requests_1_notFull,
// 					portalIfc_requests_2_enq,
// 					portalIfc_requests_2_notFull,
// 					portalIfc_requests_4_enq,
// 					portalIfc_requests_4_notFull,
// 					portalIfc_intr_status,
// 					portalIfc_intr_channel,
// 					pipes_sglist_PipeOut_first,
// 					pipes_sglist_PipeOut_deq,
// 					pipes_sglist_PipeOut_notEmpty,
// 					pipes_region_PipeOut_first,
// 					pipes_region_PipeOut_deq,
// 					pipes_region_PipeOut_notEmpty,
// 					pipes_idRequest_PipeOut_first,
// 					pipes_idRequest_PipeOut_deq,
// 					pipes_idRequest_PipeOut_notEmpty,
// 					pipes_idReturn_PipeOut_first,
// 					pipes_setInterface_PipeOut_first,
// 					pipes_setInterface_PipeOut_deq,
// 					pipes_setInterface_PipeOut_notEmpty );
// schedule portalIfc_requests_3_enq  SB ( pipes_idReturn_PipeOut_deq );
// schedule portalIfc_requests_3_enq  C ( portalIfc_requests_3_enq );
//
// schedule portalIfc_requests_3_notFull  CF ( portalIfc_messageSize_size,
// 					    portalIfc_requests_0_enq,
// 					    portalIfc_requests_0_notFull,
// 					    portalIfc_requests_1_enq,
// 					    portalIfc_requests_1_notFull,
// 					    portalIfc_requests_2_enq,
// 					    portalIfc_requests_2_notFull,
// 					    portalIfc_requests_3_notFull,
// 					    portalIfc_requests_4_enq,
// 					    portalIfc_requests_4_notFull,
// 					    portalIfc_intr_status,
// 					    portalIfc_intr_channel,
// 					    pipes_sglist_PipeOut_first,
// 					    pipes_sglist_PipeOut_deq,
// 					    pipes_sglist_PipeOut_notEmpty,
// 					    pipes_region_PipeOut_first,
// 					    pipes_region_PipeOut_deq,
// 					    pipes_region_PipeOut_notEmpty,
// 					    pipes_idRequest_PipeOut_first,
// 					    pipes_idRequest_PipeOut_deq,
// 					    pipes_idRequest_PipeOut_notEmpty,
// 					    pipes_idReturn_PipeOut_first,
// 					    pipes_idReturn_PipeOut_notEmpty,
// 					    pipes_setInterface_PipeOut_first,
// 					    pipes_setInterface_PipeOut_deq,
// 					    pipes_setInterface_PipeOut_notEmpty );
// schedule portalIfc_requests_3_notFull  SB ( portalIfc_requests_3_enq,
// 					    pipes_idReturn_PipeOut_deq );
//
// schedule portalIfc_requests_4_enq  CF ( portalIfc_messageSize_size,
// 					portalIfc_requests_0_enq,
// 					portalIfc_requests_0_notFull,
// 					portalIfc_requests_1_enq,
// 					portalIfc_requests_1_notFull,
// 					portalIfc_requests_2_enq,
// 					portalIfc_requests_2_notFull,
// 					portalIfc_requests_3_enq,
// 					portalIfc_requests_3_notFull,
// 					portalIfc_intr_status,
// 					portalIfc_intr_channel,
// 					pipes_sglist_PipeOut_first,
// 					pipes_sglist_PipeOut_deq,
// 					pipes_sglist_PipeOut_notEmpty,
// 					pipes_region_PipeOut_first,
// 					pipes_region_PipeOut_deq,
// 					pipes_region_PipeOut_notEmpty,
// 					pipes_idRequest_PipeOut_first,
// 					pipes_idRequest_PipeOut_deq,
// 					pipes_idRequest_PipeOut_notEmpty,
// 					pipes_idReturn_PipeOut_first,
// 					pipes_idReturn_PipeOut_deq,
// 					pipes_idReturn_PipeOut_notEmpty,
// 					pipes_setInterface_PipeOut_first );
// schedule portalIfc_requests_4_enq  SB ( pipes_setInterface_PipeOut_deq );
// schedule portalIfc_requests_4_enq  C ( portalIfc_requests_4_enq );
//
// schedule portalIfc_requests_4_notFull  CF ( portalIfc_messageSize_size,
// 					    portalIfc_requests_0_enq,
// 					    portalIfc_requests_0_notFull,
// 					    portalIfc_requests_1_enq,
// 					    portalIfc_requests_1_notFull,
// 					    portalIfc_requests_2_enq,
// 					    portalIfc_requests_2_notFull,
// 					    portalIfc_requests_3_enq,
// 					    portalIfc_requests_3_notFull,
// 					    portalIfc_requests_4_notFull,
// 					    portalIfc_intr_status,
// 					    portalIfc_intr_channel,
// 					    pipes_sglist_PipeOut_first,
// 					    pipes_sglist_PipeOut_deq,
// 					    pipes_sglist_PipeOut_notEmpty,
// 					    pipes_region_PipeOut_first,
// 					    pipes_region_PipeOut_deq,
// 					    pipes_region_PipeOut_notEmpty,
// 					    pipes_idRequest_PipeOut_first,
// 					    pipes_idRequest_PipeOut_deq,
// 					    pipes_idRequest_PipeOut_notEmpty,
// 					    pipes_idReturn_PipeOut_first,
// 					    pipes_idReturn_PipeOut_deq,
// 					    pipes_idReturn_PipeOut_notEmpty,
// 					    pipes_setInterface_PipeOut_first,
// 					    pipes_setInterface_PipeOut_notEmpty );
// schedule portalIfc_requests_4_notFull  SB ( portalIfc_requests_4_enq,
// 					    pipes_setInterface_PipeOut_deq );
//
// schedule portalIfc_intr_status  CF ( portalIfc_messageSize_size,
// 				     portalIfc_requests_0_enq,
// 				     portalIfc_requests_0_notFull,
// 				     portalIfc_requests_1_enq,
// 				     portalIfc_requests_1_notFull,
// 				     portalIfc_requests_2_enq,
// 				     portalIfc_requests_2_notFull,
// 				     portalIfc_requests_3_enq,
// 				     portalIfc_requests_3_notFull,
// 				     portalIfc_requests_4_enq,
// 				     portalIfc_requests_4_notFull,
// 				     portalIfc_intr_status,
// 				     portalIfc_intr_channel,
// 				     pipes_sglist_PipeOut_first,
// 				     pipes_sglist_PipeOut_deq,
// 				     pipes_sglist_PipeOut_notEmpty,
// 				     pipes_region_PipeOut_first,
// 				     pipes_region_PipeOut_deq,
// 				     pipes_region_PipeOut_notEmpty,
// 				     pipes_idRequest_PipeOut_first,
// 				     pipes_idRequest_PipeOut_deq,
// 				     pipes_idRequest_PipeOut_notEmpty,
// 				     pipes_idReturn_PipeOut_first,
// 				     pipes_idReturn_PipeOut_deq,
// 				     pipes_idReturn_PipeOut_notEmpty,
// 				     pipes_setInterface_PipeOut_first,
// 				     pipes_setInterface_PipeOut_deq,
// 				     pipes_setInterface_PipeOut_notEmpty );
//
// schedule portalIfc_intr_channel  CF ( portalIfc_messageSize_size,
// 				      portalIfc_requests_0_enq,
// 				      portalIfc_requests_0_notFull,
// 				      portalIfc_requests_1_enq,
// 				      portalIfc_requests_1_notFull,
// 				      portalIfc_requests_2_enq,
// 				      portalIfc_requests_2_notFull,
// 				      portalIfc_requests_3_enq,
// 				      portalIfc_requests_3_notFull,
// 				      portalIfc_requests_4_enq,
// 				      portalIfc_requests_4_notFull,
// 				      portalIfc_intr_status,
// 				      portalIfc_intr_channel,
// 				      pipes_sglist_PipeOut_first,
// 				      pipes_sglist_PipeOut_deq,
// 				      pipes_sglist_PipeOut_notEmpty,
// 				      pipes_region_PipeOut_first,
// 				      pipes_region_PipeOut_deq,
// 				      pipes_region_PipeOut_notEmpty,
// 				      pipes_idRequest_PipeOut_first,
// 				      pipes_idRequest_PipeOut_deq,
// 				      pipes_idRequest_PipeOut_notEmpty,
// 				      pipes_idReturn_PipeOut_first,
// 				      pipes_idReturn_PipeOut_deq,
// 				      pipes_idReturn_PipeOut_notEmpty,
// 				      pipes_setInterface_PipeOut_first,
// 				      pipes_setInterface_PipeOut_deq,
// 				      pipes_setInterface_PipeOut_notEmpty );
//
// schedule pipes_sglist_PipeOut_first  CF ( portalIfc_messageSize_size,
// 					  portalIfc_requests_0_enq,
// 					  portalIfc_requests_0_notFull,
// 					  portalIfc_requests_1_enq,
// 					  portalIfc_requests_1_notFull,
// 					  portalIfc_requests_2_enq,
// 					  portalIfc_requests_2_notFull,
// 					  portalIfc_requests_3_enq,
// 					  portalIfc_requests_3_notFull,
// 					  portalIfc_requests_4_enq,
// 					  portalIfc_requests_4_notFull,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel,
// 					  pipes_sglist_PipeOut_first,
// 					  pipes_sglist_PipeOut_notEmpty,
// 					  pipes_region_PipeOut_first,
// 					  pipes_region_PipeOut_deq,
// 					  pipes_region_PipeOut_notEmpty,
// 					  pipes_idRequest_PipeOut_first,
// 					  pipes_idRequest_PipeOut_deq,
// 					  pipes_idRequest_PipeOut_notEmpty,
// 					  pipes_idReturn_PipeOut_first,
// 					  pipes_idReturn_PipeOut_deq,
// 					  pipes_idReturn_PipeOut_notEmpty,
// 					  pipes_setInterface_PipeOut_first,
// 					  pipes_setInterface_PipeOut_deq,
// 					  pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_sglist_PipeOut_first  SB ( pipes_sglist_PipeOut_deq );
//
// schedule pipes_sglist_PipeOut_deq  CF ( portalIfc_messageSize_size,
// 					portalIfc_requests_1_enq,
// 					portalIfc_requests_1_notFull,
// 					portalIfc_requests_2_enq,
// 					portalIfc_requests_2_notFull,
// 					portalIfc_requests_3_enq,
// 					portalIfc_requests_3_notFull,
// 					portalIfc_requests_4_enq,
// 					portalIfc_requests_4_notFull,
// 					portalIfc_intr_status,
// 					portalIfc_intr_channel,
// 					pipes_region_PipeOut_first,
// 					pipes_region_PipeOut_deq,
// 					pipes_region_PipeOut_notEmpty,
// 					pipes_idRequest_PipeOut_first,
// 					pipes_idRequest_PipeOut_deq,
// 					pipes_idRequest_PipeOut_notEmpty,
// 					pipes_idReturn_PipeOut_first,
// 					pipes_idReturn_PipeOut_deq,
// 					pipes_idReturn_PipeOut_notEmpty,
// 					pipes_setInterface_PipeOut_first,
// 					pipes_setInterface_PipeOut_deq,
// 					pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_sglist_PipeOut_deq  C ( pipes_sglist_PipeOut_deq );
//
// schedule pipes_sglist_PipeOut_notEmpty  CF ( portalIfc_messageSize_size,
// 					     portalIfc_requests_0_notFull,
// 					     portalIfc_requests_1_enq,
// 					     portalIfc_requests_1_notFull,
// 					     portalIfc_requests_2_enq,
// 					     portalIfc_requests_2_notFull,
// 					     portalIfc_requests_3_enq,
// 					     portalIfc_requests_3_notFull,
// 					     portalIfc_requests_4_enq,
// 					     portalIfc_requests_4_notFull,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     pipes_sglist_PipeOut_first,
// 					     pipes_sglist_PipeOut_notEmpty,
// 					     pipes_region_PipeOut_first,
// 					     pipes_region_PipeOut_deq,
// 					     pipes_region_PipeOut_notEmpty,
// 					     pipes_idRequest_PipeOut_first,
// 					     pipes_idRequest_PipeOut_deq,
// 					     pipes_idRequest_PipeOut_notEmpty,
// 					     pipes_idReturn_PipeOut_first,
// 					     pipes_idReturn_PipeOut_deq,
// 					     pipes_idReturn_PipeOut_notEmpty,
// 					     pipes_setInterface_PipeOut_first,
// 					     pipes_setInterface_PipeOut_deq,
// 					     pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_sglist_PipeOut_notEmpty  SB ( portalIfc_requests_0_enq,
// 					     pipes_sglist_PipeOut_deq );
//
// schedule pipes_region_PipeOut_first  CF ( portalIfc_messageSize_size,
// 					  portalIfc_requests_0_enq,
// 					  portalIfc_requests_0_notFull,
// 					  portalIfc_requests_1_enq,
// 					  portalIfc_requests_1_notFull,
// 					  portalIfc_requests_2_enq,
// 					  portalIfc_requests_2_notFull,
// 					  portalIfc_requests_3_enq,
// 					  portalIfc_requests_3_notFull,
// 					  portalIfc_requests_4_enq,
// 					  portalIfc_requests_4_notFull,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel,
// 					  pipes_sglist_PipeOut_first,
// 					  pipes_sglist_PipeOut_deq,
// 					  pipes_sglist_PipeOut_notEmpty,
// 					  pipes_region_PipeOut_first,
// 					  pipes_region_PipeOut_notEmpty,
// 					  pipes_idRequest_PipeOut_first,
// 					  pipes_idRequest_PipeOut_deq,
// 					  pipes_idRequest_PipeOut_notEmpty,
// 					  pipes_idReturn_PipeOut_first,
// 					  pipes_idReturn_PipeOut_deq,
// 					  pipes_idReturn_PipeOut_notEmpty,
// 					  pipes_setInterface_PipeOut_first,
// 					  pipes_setInterface_PipeOut_deq,
// 					  pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_region_PipeOut_first  SB ( pipes_region_PipeOut_deq );
//
// schedule pipes_region_PipeOut_deq  CF ( portalIfc_messageSize_size,
// 					portalIfc_requests_0_enq,
// 					portalIfc_requests_0_notFull,
// 					portalIfc_requests_2_enq,
// 					portalIfc_requests_2_notFull,
// 					portalIfc_requests_3_enq,
// 					portalIfc_requests_3_notFull,
// 					portalIfc_requests_4_enq,
// 					portalIfc_requests_4_notFull,
// 					portalIfc_intr_status,
// 					portalIfc_intr_channel,
// 					pipes_sglist_PipeOut_first,
// 					pipes_sglist_PipeOut_deq,
// 					pipes_sglist_PipeOut_notEmpty,
// 					pipes_idRequest_PipeOut_first,
// 					pipes_idRequest_PipeOut_deq,
// 					pipes_idRequest_PipeOut_notEmpty,
// 					pipes_idReturn_PipeOut_first,
// 					pipes_idReturn_PipeOut_deq,
// 					pipes_idReturn_PipeOut_notEmpty,
// 					pipes_setInterface_PipeOut_first,
// 					pipes_setInterface_PipeOut_deq,
// 					pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_region_PipeOut_deq  C ( pipes_region_PipeOut_deq );
//
// schedule pipes_region_PipeOut_notEmpty  CF ( portalIfc_messageSize_size,
// 					     portalIfc_requests_0_enq,
// 					     portalIfc_requests_0_notFull,
// 					     portalIfc_requests_1_notFull,
// 					     portalIfc_requests_2_enq,
// 					     portalIfc_requests_2_notFull,
// 					     portalIfc_requests_3_enq,
// 					     portalIfc_requests_3_notFull,
// 					     portalIfc_requests_4_enq,
// 					     portalIfc_requests_4_notFull,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     pipes_sglist_PipeOut_first,
// 					     pipes_sglist_PipeOut_deq,
// 					     pipes_sglist_PipeOut_notEmpty,
// 					     pipes_region_PipeOut_first,
// 					     pipes_region_PipeOut_notEmpty,
// 					     pipes_idRequest_PipeOut_first,
// 					     pipes_idRequest_PipeOut_deq,
// 					     pipes_idRequest_PipeOut_notEmpty,
// 					     pipes_idReturn_PipeOut_first,
// 					     pipes_idReturn_PipeOut_deq,
// 					     pipes_idReturn_PipeOut_notEmpty,
// 					     pipes_setInterface_PipeOut_first,
// 					     pipes_setInterface_PipeOut_deq,
// 					     pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_region_PipeOut_notEmpty  SB ( portalIfc_requests_1_enq,
// 					     pipes_region_PipeOut_deq );
//
// schedule pipes_idRequest_PipeOut_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_requests_0_enq,
// 					     portalIfc_requests_0_notFull,
// 					     portalIfc_requests_1_enq,
// 					     portalIfc_requests_1_notFull,
// 					     portalIfc_requests_2_enq,
// 					     portalIfc_requests_2_notFull,
// 					     portalIfc_requests_3_enq,
// 					     portalIfc_requests_3_notFull,
// 					     portalIfc_requests_4_enq,
// 					     portalIfc_requests_4_notFull,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     pipes_sglist_PipeOut_first,
// 					     pipes_sglist_PipeOut_deq,
// 					     pipes_sglist_PipeOut_notEmpty,
// 					     pipes_region_PipeOut_first,
// 					     pipes_region_PipeOut_deq,
// 					     pipes_region_PipeOut_notEmpty,
// 					     pipes_idRequest_PipeOut_first,
// 					     pipes_idRequest_PipeOut_notEmpty,
// 					     pipes_idReturn_PipeOut_first,
// 					     pipes_idReturn_PipeOut_deq,
// 					     pipes_idReturn_PipeOut_notEmpty,
// 					     pipes_setInterface_PipeOut_first,
// 					     pipes_setInterface_PipeOut_deq,
// 					     pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_idRequest_PipeOut_first  SB ( pipes_idRequest_PipeOut_deq );
//
// schedule pipes_idRequest_PipeOut_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_requests_0_enq,
// 					   portalIfc_requests_0_notFull,
// 					   portalIfc_requests_1_enq,
// 					   portalIfc_requests_1_notFull,
// 					   portalIfc_requests_3_enq,
// 					   portalIfc_requests_3_notFull,
// 					   portalIfc_requests_4_enq,
// 					   portalIfc_requests_4_notFull,
// 					   portalIfc_intr_status,
// 					   portalIfc_intr_channel,
// 					   pipes_sglist_PipeOut_first,
// 					   pipes_sglist_PipeOut_deq,
// 					   pipes_sglist_PipeOut_notEmpty,
// 					   pipes_region_PipeOut_first,
// 					   pipes_region_PipeOut_deq,
// 					   pipes_region_PipeOut_notEmpty,
// 					   pipes_idReturn_PipeOut_first,
// 					   pipes_idReturn_PipeOut_deq,
// 					   pipes_idReturn_PipeOut_notEmpty,
// 					   pipes_setInterface_PipeOut_first,
// 					   pipes_setInterface_PipeOut_deq,
// 					   pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_idRequest_PipeOut_deq  C ( pipes_idRequest_PipeOut_deq );
//
// schedule pipes_idRequest_PipeOut_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_requests_0_enq,
// 						portalIfc_requests_0_notFull,
// 						portalIfc_requests_1_enq,
// 						portalIfc_requests_1_notFull,
// 						portalIfc_requests_2_notFull,
// 						portalIfc_requests_3_enq,
// 						portalIfc_requests_3_notFull,
// 						portalIfc_requests_4_enq,
// 						portalIfc_requests_4_notFull,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						pipes_sglist_PipeOut_first,
// 						pipes_sglist_PipeOut_deq,
// 						pipes_sglist_PipeOut_notEmpty,
// 						pipes_region_PipeOut_first,
// 						pipes_region_PipeOut_deq,
// 						pipes_region_PipeOut_notEmpty,
// 						pipes_idRequest_PipeOut_first,
// 						pipes_idRequest_PipeOut_notEmpty,
// 						pipes_idReturn_PipeOut_first,
// 						pipes_idReturn_PipeOut_deq,
// 						pipes_idReturn_PipeOut_notEmpty,
// 						pipes_setInterface_PipeOut_first,
// 						pipes_setInterface_PipeOut_deq,
// 						pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_idRequest_PipeOut_notEmpty  SB ( portalIfc_requests_2_enq,
// 						pipes_idRequest_PipeOut_deq );
//
// schedule pipes_idReturn_PipeOut_first  CF ( portalIfc_messageSize_size,
// 					    portalIfc_requests_0_enq,
// 					    portalIfc_requests_0_notFull,
// 					    portalIfc_requests_1_enq,
// 					    portalIfc_requests_1_notFull,
// 					    portalIfc_requests_2_enq,
// 					    portalIfc_requests_2_notFull,
// 					    portalIfc_requests_3_enq,
// 					    portalIfc_requests_3_notFull,
// 					    portalIfc_requests_4_enq,
// 					    portalIfc_requests_4_notFull,
// 					    portalIfc_intr_status,
// 					    portalIfc_intr_channel,
// 					    pipes_sglist_PipeOut_first,
// 					    pipes_sglist_PipeOut_deq,
// 					    pipes_sglist_PipeOut_notEmpty,
// 					    pipes_region_PipeOut_first,
// 					    pipes_region_PipeOut_deq,
// 					    pipes_region_PipeOut_notEmpty,
// 					    pipes_idRequest_PipeOut_first,
// 					    pipes_idRequest_PipeOut_deq,
// 					    pipes_idRequest_PipeOut_notEmpty,
// 					    pipes_idReturn_PipeOut_first,
// 					    pipes_idReturn_PipeOut_notEmpty,
// 					    pipes_setInterface_PipeOut_first,
// 					    pipes_setInterface_PipeOut_deq,
// 					    pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_idReturn_PipeOut_first  SB ( pipes_idReturn_PipeOut_deq );
//
// schedule pipes_idReturn_PipeOut_deq  CF ( portalIfc_messageSize_size,
// 					  portalIfc_requests_0_enq,
// 					  portalIfc_requests_0_notFull,
// 					  portalIfc_requests_1_enq,
// 					  portalIfc_requests_1_notFull,
// 					  portalIfc_requests_2_enq,
// 					  portalIfc_requests_2_notFull,
// 					  portalIfc_requests_4_enq,
// 					  portalIfc_requests_4_notFull,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel,
// 					  pipes_sglist_PipeOut_first,
// 					  pipes_sglist_PipeOut_deq,
// 					  pipes_sglist_PipeOut_notEmpty,
// 					  pipes_region_PipeOut_first,
// 					  pipes_region_PipeOut_deq,
// 					  pipes_region_PipeOut_notEmpty,
// 					  pipes_idRequest_PipeOut_first,
// 					  pipes_idRequest_PipeOut_deq,
// 					  pipes_idRequest_PipeOut_notEmpty,
// 					  pipes_setInterface_PipeOut_first,
// 					  pipes_setInterface_PipeOut_deq,
// 					  pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_idReturn_PipeOut_deq  C ( pipes_idReturn_PipeOut_deq );
//
// schedule pipes_idReturn_PipeOut_notEmpty  CF ( portalIfc_messageSize_size,
// 					       portalIfc_requests_0_enq,
// 					       portalIfc_requests_0_notFull,
// 					       portalIfc_requests_1_enq,
// 					       portalIfc_requests_1_notFull,
// 					       portalIfc_requests_2_enq,
// 					       portalIfc_requests_2_notFull,
// 					       portalIfc_requests_3_notFull,
// 					       portalIfc_requests_4_enq,
// 					       portalIfc_requests_4_notFull,
// 					       portalIfc_intr_status,
// 					       portalIfc_intr_channel,
// 					       pipes_sglist_PipeOut_first,
// 					       pipes_sglist_PipeOut_deq,
// 					       pipes_sglist_PipeOut_notEmpty,
// 					       pipes_region_PipeOut_first,
// 					       pipes_region_PipeOut_deq,
// 					       pipes_region_PipeOut_notEmpty,
// 					       pipes_idRequest_PipeOut_first,
// 					       pipes_idRequest_PipeOut_deq,
// 					       pipes_idRequest_PipeOut_notEmpty,
// 					       pipes_idReturn_PipeOut_first,
// 					       pipes_idReturn_PipeOut_notEmpty,
// 					       pipes_setInterface_PipeOut_first,
// 					       pipes_setInterface_PipeOut_deq,
// 					       pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_idReturn_PipeOut_notEmpty  SB ( portalIfc_requests_3_enq,
// 					       pipes_idReturn_PipeOut_deq );
//
// schedule pipes_setInterface_PipeOut_first  CF ( portalIfc_messageSize_size,
// 						portalIfc_requests_0_enq,
// 						portalIfc_requests_0_notFull,
// 						portalIfc_requests_1_enq,
// 						portalIfc_requests_1_notFull,
// 						portalIfc_requests_2_enq,
// 						portalIfc_requests_2_notFull,
// 						portalIfc_requests_3_enq,
// 						portalIfc_requests_3_notFull,
// 						portalIfc_requests_4_enq,
// 						portalIfc_requests_4_notFull,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						pipes_sglist_PipeOut_first,
// 						pipes_sglist_PipeOut_deq,
// 						pipes_sglist_PipeOut_notEmpty,
// 						pipes_region_PipeOut_first,
// 						pipes_region_PipeOut_deq,
// 						pipes_region_PipeOut_notEmpty,
// 						pipes_idRequest_PipeOut_first,
// 						pipes_idRequest_PipeOut_deq,
// 						pipes_idRequest_PipeOut_notEmpty,
// 						pipes_idReturn_PipeOut_first,
// 						pipes_idReturn_PipeOut_deq,
// 						pipes_idReturn_PipeOut_notEmpty,
// 						pipes_setInterface_PipeOut_first,
// 						pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_setInterface_PipeOut_first  SB ( pipes_setInterface_PipeOut_deq );
//
// schedule pipes_setInterface_PipeOut_deq  CF ( portalIfc_messageSize_size,
// 					      portalIfc_requests_0_enq,
// 					      portalIfc_requests_0_notFull,
// 					      portalIfc_requests_1_enq,
// 					      portalIfc_requests_1_notFull,
// 					      portalIfc_requests_2_enq,
// 					      portalIfc_requests_2_notFull,
// 					      portalIfc_requests_3_enq,
// 					      portalIfc_requests_3_notFull,
// 					      portalIfc_intr_status,
// 					      portalIfc_intr_channel,
// 					      pipes_sglist_PipeOut_first,
// 					      pipes_sglist_PipeOut_deq,
// 					      pipes_sglist_PipeOut_notEmpty,
// 					      pipes_region_PipeOut_first,
// 					      pipes_region_PipeOut_deq,
// 					      pipes_region_PipeOut_notEmpty,
// 					      pipes_idRequest_PipeOut_first,
// 					      pipes_idRequest_PipeOut_deq,
// 					      pipes_idRequest_PipeOut_notEmpty,
// 					      pipes_idReturn_PipeOut_first,
// 					      pipes_idReturn_PipeOut_deq,
// 					      pipes_idReturn_PipeOut_notEmpty );
// schedule pipes_setInterface_PipeOut_deq  C ( pipes_setInterface_PipeOut_deq );
//
// schedule pipes_setInterface_PipeOut_notEmpty  CF ( portalIfc_messageSize_size,
// 						   portalIfc_requests_0_enq,
// 						   portalIfc_requests_0_notFull,
// 						   portalIfc_requests_1_enq,
// 						   portalIfc_requests_1_notFull,
// 						   portalIfc_requests_2_enq,
// 						   portalIfc_requests_2_notFull,
// 						   portalIfc_requests_3_enq,
// 						   portalIfc_requests_3_notFull,
// 						   portalIfc_requests_4_notFull,
// 						   portalIfc_intr_status,
// 						   portalIfc_intr_channel,
// 						   pipes_sglist_PipeOut_first,
// 						   pipes_sglist_PipeOut_deq,
// 						   pipes_sglist_PipeOut_notEmpty,
// 						   pipes_region_PipeOut_first,
// 						   pipes_region_PipeOut_deq,
// 						   pipes_region_PipeOut_notEmpty,
// 						   pipes_idRequest_PipeOut_first,
// 						   pipes_idRequest_PipeOut_deq,
// 						   pipes_idRequest_PipeOut_notEmpty,
// 						   pipes_idReturn_PipeOut_first,
// 						   pipes_idReturn_PipeOut_deq,
// 						   pipes_idReturn_PipeOut_notEmpty,
// 						   pipes_setInterface_PipeOut_first,
// 						   pipes_setInterface_PipeOut_notEmpty );
// schedule pipes_setInterface_PipeOut_notEmpty  SB ( portalIfc_requests_4_enq,
// 						   pipes_setInterface_PipeOut_deq );
//
//
// Ports:
// Name                         I/O  size props
// portalIfc_messageSize_size     O    16
// RDY_portalIfc_messageSize_size  O     1 const
// RDY_portalIfc_requests_0_enq   O     1
// portalIfc_requests_0_notFull   O     1 reg
// RDY_portalIfc_requests_0_notFull  O     1 const
// RDY_portalIfc_requests_1_enq   O     1
// portalIfc_requests_1_notFull   O     1 reg
// RDY_portalIfc_requests_1_notFull  O     1 const
// RDY_portalIfc_requests_2_enq   O     1 reg
// portalIfc_requests_2_notFull   O     1 reg
// RDY_portalIfc_requests_2_notFull  O     1 const
// RDY_portalIfc_requests_3_enq   O     1 reg
// portalIfc_requests_3_notFull   O     1 reg
// RDY_portalIfc_requests_3_notFull  O     1 const
// RDY_portalIfc_requests_4_enq   O     1
// portalIfc_requests_4_notFull   O     1 reg
// RDY_portalIfc_requests_4_notFull  O     1 const
// portalIfc_intr_status          O     1 const
// RDY_portalIfc_intr_status      O     1 const
// portalIfc_intr_channel         O    32 const
// RDY_portalIfc_intr_channel     O     1 const
// pipes_sglist_PipeOut_first     O   160 reg
// RDY_pipes_sglist_PipeOut_first  O     1 reg
// RDY_pipes_sglist_PipeOut_deq   O     1 reg
// pipes_sglist_PipeOut_notEmpty  O     1 reg
// RDY_pipes_sglist_PipeOut_notEmpty  O     1 const
// pipes_region_PipeOut_first     O   416 reg
// RDY_pipes_region_PipeOut_first  O     1 reg
// RDY_pipes_region_PipeOut_deq   O     1 reg
// pipes_region_PipeOut_notEmpty  O     1 reg
// RDY_pipes_region_PipeOut_notEmpty  O     1 const
// pipes_idRequest_PipeOut_first  O    32 reg
// RDY_pipes_idRequest_PipeOut_first  O     1 reg
// RDY_pipes_idRequest_PipeOut_deq  O     1 reg
// pipes_idRequest_PipeOut_notEmpty  O     1 reg
// RDY_pipes_idRequest_PipeOut_notEmpty  O     1 const
// pipes_idReturn_PipeOut_first   O    32 reg
// RDY_pipes_idReturn_PipeOut_first  O     1 reg
// RDY_pipes_idReturn_PipeOut_deq  O     1 reg
// pipes_idReturn_PipeOut_notEmpty  O     1 reg
// RDY_pipes_idReturn_PipeOut_notEmpty  O     1 const
// pipes_setInterface_PipeOut_first  O    64 reg
// RDY_pipes_setInterface_PipeOut_first  O     1 reg
// RDY_pipes_setInterface_PipeOut_deq  O     1 reg
// pipes_setInterface_PipeOut_notEmpty  O     1 reg
// RDY_pipes_setInterface_PipeOut_notEmpty  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// portalIfc_messageSize_size_methodNumber  I    16
// portalIfc_requests_0_enq_v     I    32 reg
// portalIfc_requests_1_enq_v     I    32 reg
// portalIfc_requests_2_enq_v     I    32 reg
// portalIfc_requests_3_enq_v     I    32 reg
// portalIfc_requests_4_enq_v     I    32 reg
// EN_portalIfc_requests_0_enq    I     1
// EN_portalIfc_requests_1_enq    I     1
// EN_portalIfc_requests_2_enq    I     1
// EN_portalIfc_requests_3_enq    I     1
// EN_portalIfc_requests_4_enq    I     1
// EN_pipes_sglist_PipeOut_deq    I     1
// EN_pipes_region_PipeOut_deq    I     1
// EN_pipes_idRequest_PipeOut_deq  I     1
// EN_pipes_idReturn_PipeOut_deq  I     1
// EN_pipes_setInterface_PipeOut_deq  I     1
//
// Combinational paths from inputs to outputs:
//   portalIfc_messageSize_size_methodNumber -> portalIfc_messageSize_size
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMMURequestInput(CLK,
			 RST_N,

			 portalIfc_messageSize_size_methodNumber,
			 portalIfc_messageSize_size,
			 RDY_portalIfc_messageSize_size,

			 portalIfc_requests_0_enq_v,
			 EN_portalIfc_requests_0_enq,
			 RDY_portalIfc_requests_0_enq,

			 portalIfc_requests_0_notFull,
			 RDY_portalIfc_requests_0_notFull,

			 portalIfc_requests_1_enq_v,
			 EN_portalIfc_requests_1_enq,
			 RDY_portalIfc_requests_1_enq,

			 portalIfc_requests_1_notFull,
			 RDY_portalIfc_requests_1_notFull,

			 portalIfc_requests_2_enq_v,
			 EN_portalIfc_requests_2_enq,
			 RDY_portalIfc_requests_2_enq,

			 portalIfc_requests_2_notFull,
			 RDY_portalIfc_requests_2_notFull,

			 portalIfc_requests_3_enq_v,
			 EN_portalIfc_requests_3_enq,
			 RDY_portalIfc_requests_3_enq,

			 portalIfc_requests_3_notFull,
			 RDY_portalIfc_requests_3_notFull,

			 portalIfc_requests_4_enq_v,
			 EN_portalIfc_requests_4_enq,
			 RDY_portalIfc_requests_4_enq,

			 portalIfc_requests_4_notFull,
			 RDY_portalIfc_requests_4_notFull,

			 portalIfc_intr_status,
			 RDY_portalIfc_intr_status,

			 portalIfc_intr_channel,
			 RDY_portalIfc_intr_channel,

			 pipes_sglist_PipeOut_first,
			 RDY_pipes_sglist_PipeOut_first,

			 EN_pipes_sglist_PipeOut_deq,
			 RDY_pipes_sglist_PipeOut_deq,

			 pipes_sglist_PipeOut_notEmpty,
			 RDY_pipes_sglist_PipeOut_notEmpty,

			 pipes_region_PipeOut_first,
			 RDY_pipes_region_PipeOut_first,

			 EN_pipes_region_PipeOut_deq,
			 RDY_pipes_region_PipeOut_deq,

			 pipes_region_PipeOut_notEmpty,
			 RDY_pipes_region_PipeOut_notEmpty,

			 pipes_idRequest_PipeOut_first,
			 RDY_pipes_idRequest_PipeOut_first,

			 EN_pipes_idRequest_PipeOut_deq,
			 RDY_pipes_idRequest_PipeOut_deq,

			 pipes_idRequest_PipeOut_notEmpty,
			 RDY_pipes_idRequest_PipeOut_notEmpty,

			 pipes_idReturn_PipeOut_first,
			 RDY_pipes_idReturn_PipeOut_first,

			 EN_pipes_idReturn_PipeOut_deq,
			 RDY_pipes_idReturn_PipeOut_deq,

			 pipes_idReturn_PipeOut_notEmpty,
			 RDY_pipes_idReturn_PipeOut_notEmpty,

			 pipes_setInterface_PipeOut_first,
			 RDY_pipes_setInterface_PipeOut_first,

			 EN_pipes_setInterface_PipeOut_deq,
			 RDY_pipes_setInterface_PipeOut_deq,

			 pipes_setInterface_PipeOut_notEmpty,
			 RDY_pipes_setInterface_PipeOut_notEmpty);
  input  CLK;
  input  RST_N;

  // value method portalIfc_messageSize_size
  input  [15 : 0] portalIfc_messageSize_size_methodNumber;
  output [15 : 0] portalIfc_messageSize_size;
  output RDY_portalIfc_messageSize_size;

  // action method portalIfc_requests_0_enq
  input  [31 : 0] portalIfc_requests_0_enq_v;
  input  EN_portalIfc_requests_0_enq;
  output RDY_portalIfc_requests_0_enq;

  // value method portalIfc_requests_0_notFull
  output portalIfc_requests_0_notFull;
  output RDY_portalIfc_requests_0_notFull;

  // action method portalIfc_requests_1_enq
  input  [31 : 0] portalIfc_requests_1_enq_v;
  input  EN_portalIfc_requests_1_enq;
  output RDY_portalIfc_requests_1_enq;

  // value method portalIfc_requests_1_notFull
  output portalIfc_requests_1_notFull;
  output RDY_portalIfc_requests_1_notFull;

  // action method portalIfc_requests_2_enq
  input  [31 : 0] portalIfc_requests_2_enq_v;
  input  EN_portalIfc_requests_2_enq;
  output RDY_portalIfc_requests_2_enq;

  // value method portalIfc_requests_2_notFull
  output portalIfc_requests_2_notFull;
  output RDY_portalIfc_requests_2_notFull;

  // action method portalIfc_requests_3_enq
  input  [31 : 0] portalIfc_requests_3_enq_v;
  input  EN_portalIfc_requests_3_enq;
  output RDY_portalIfc_requests_3_enq;

  // value method portalIfc_requests_3_notFull
  output portalIfc_requests_3_notFull;
  output RDY_portalIfc_requests_3_notFull;

  // action method portalIfc_requests_4_enq
  input  [31 : 0] portalIfc_requests_4_enq_v;
  input  EN_portalIfc_requests_4_enq;
  output RDY_portalIfc_requests_4_enq;

  // value method portalIfc_requests_4_notFull
  output portalIfc_requests_4_notFull;
  output RDY_portalIfc_requests_4_notFull;

  // value method portalIfc_intr_status
  output portalIfc_intr_status;
  output RDY_portalIfc_intr_status;

  // value method portalIfc_intr_channel
  output [31 : 0] portalIfc_intr_channel;
  output RDY_portalIfc_intr_channel;

  // value method pipes_sglist_PipeOut_first
  output [159 : 0] pipes_sglist_PipeOut_first;
  output RDY_pipes_sglist_PipeOut_first;

  // action method pipes_sglist_PipeOut_deq
  input  EN_pipes_sglist_PipeOut_deq;
  output RDY_pipes_sglist_PipeOut_deq;

  // value method pipes_sglist_PipeOut_notEmpty
  output pipes_sglist_PipeOut_notEmpty;
  output RDY_pipes_sglist_PipeOut_notEmpty;

  // value method pipes_region_PipeOut_first
  output [415 : 0] pipes_region_PipeOut_first;
  output RDY_pipes_region_PipeOut_first;

  // action method pipes_region_PipeOut_deq
  input  EN_pipes_region_PipeOut_deq;
  output RDY_pipes_region_PipeOut_deq;

  // value method pipes_region_PipeOut_notEmpty
  output pipes_region_PipeOut_notEmpty;
  output RDY_pipes_region_PipeOut_notEmpty;

  // value method pipes_idRequest_PipeOut_first
  output [31 : 0] pipes_idRequest_PipeOut_first;
  output RDY_pipes_idRequest_PipeOut_first;

  // action method pipes_idRequest_PipeOut_deq
  input  EN_pipes_idRequest_PipeOut_deq;
  output RDY_pipes_idRequest_PipeOut_deq;

  // value method pipes_idRequest_PipeOut_notEmpty
  output pipes_idRequest_PipeOut_notEmpty;
  output RDY_pipes_idRequest_PipeOut_notEmpty;

  // value method pipes_idReturn_PipeOut_first
  output [31 : 0] pipes_idReturn_PipeOut_first;
  output RDY_pipes_idReturn_PipeOut_first;

  // action method pipes_idReturn_PipeOut_deq
  input  EN_pipes_idReturn_PipeOut_deq;
  output RDY_pipes_idReturn_PipeOut_deq;

  // value method pipes_idReturn_PipeOut_notEmpty
  output pipes_idReturn_PipeOut_notEmpty;
  output RDY_pipes_idReturn_PipeOut_notEmpty;

  // value method pipes_setInterface_PipeOut_first
  output [63 : 0] pipes_setInterface_PipeOut_first;
  output RDY_pipes_setInterface_PipeOut_first;

  // action method pipes_setInterface_PipeOut_deq
  input  EN_pipes_setInterface_PipeOut_deq;
  output RDY_pipes_setInterface_PipeOut_deq;

  // value method pipes_setInterface_PipeOut_notEmpty
  output pipes_setInterface_PipeOut_notEmpty;
  output RDY_pipes_setInterface_PipeOut_notEmpty;

  // signals for module outputs
  reg [15 : 0] portalIfc_messageSize_size;
  wire [415 : 0] pipes_region_PipeOut_first;
  wire [159 : 0] pipes_sglist_PipeOut_first;
  wire [63 : 0] pipes_setInterface_PipeOut_first;
  wire [31 : 0] pipes_idRequest_PipeOut_first,
		pipes_idReturn_PipeOut_first,
		portalIfc_intr_channel;
  wire RDY_pipes_idRequest_PipeOut_deq,
       RDY_pipes_idRequest_PipeOut_first,
       RDY_pipes_idRequest_PipeOut_notEmpty,
       RDY_pipes_idReturn_PipeOut_deq,
       RDY_pipes_idReturn_PipeOut_first,
       RDY_pipes_idReturn_PipeOut_notEmpty,
       RDY_pipes_region_PipeOut_deq,
       RDY_pipes_region_PipeOut_first,
       RDY_pipes_region_PipeOut_notEmpty,
       RDY_pipes_setInterface_PipeOut_deq,
       RDY_pipes_setInterface_PipeOut_first,
       RDY_pipes_setInterface_PipeOut_notEmpty,
       RDY_pipes_sglist_PipeOut_deq,
       RDY_pipes_sglist_PipeOut_first,
       RDY_pipes_sglist_PipeOut_notEmpty,
       RDY_portalIfc_intr_channel,
       RDY_portalIfc_intr_status,
       RDY_portalIfc_messageSize_size,
       RDY_portalIfc_requests_0_enq,
       RDY_portalIfc_requests_0_notFull,
       RDY_portalIfc_requests_1_enq,
       RDY_portalIfc_requests_1_notFull,
       RDY_portalIfc_requests_2_enq,
       RDY_portalIfc_requests_2_notFull,
       RDY_portalIfc_requests_3_enq,
       RDY_portalIfc_requests_3_notFull,
       RDY_portalIfc_requests_4_enq,
       RDY_portalIfc_requests_4_notFull,
       pipes_idRequest_PipeOut_notEmpty,
       pipes_idReturn_PipeOut_notEmpty,
       pipes_region_PipeOut_notEmpty,
       pipes_setInterface_PipeOut_notEmpty,
       pipes_sglist_PipeOut_notEmpty,
       portalIfc_intr_status,
       portalIfc_requests_0_notFull,
       portalIfc_requests_1_notFull,
       portalIfc_requests_2_notFull,
       portalIfc_requests_3_notFull,
       portalIfc_requests_4_notFull;

  // register idRequest_requestAdapter_fbnbuff
  reg [31 : 0] idRequest_requestAdapter_fbnbuff;
  wire [31 : 0] idRequest_requestAdapter_fbnbuff_D_IN;
  wire idRequest_requestAdapter_fbnbuff_EN;

  // register idReturn_requestAdapter_fbnbuff
  reg [31 : 0] idReturn_requestAdapter_fbnbuff;
  wire [31 : 0] idReturn_requestAdapter_fbnbuff_D_IN;
  wire idReturn_requestAdapter_fbnbuff_EN;

  // register region_requestAdapter_count
  reg [3 : 0] region_requestAdapter_count;
  wire [3 : 0] region_requestAdapter_count_D_IN;
  wire region_requestAdapter_count_EN;

  // register region_requestAdapter_fbnbuff
  reg [415 : 0] region_requestAdapter_fbnbuff;
  wire [415 : 0] region_requestAdapter_fbnbuff_D_IN;
  wire region_requestAdapter_fbnbuff_EN;

  // register setInterface_requestAdapter_count
  reg setInterface_requestAdapter_count;
  wire setInterface_requestAdapter_count_D_IN,
       setInterface_requestAdapter_count_EN;

  // register setInterface_requestAdapter_fbnbuff
  reg [63 : 0] setInterface_requestAdapter_fbnbuff;
  wire [63 : 0] setInterface_requestAdapter_fbnbuff_D_IN;
  wire setInterface_requestAdapter_fbnbuff_EN;

  // register sglist_requestAdapter_count
  reg [2 : 0] sglist_requestAdapter_count;
  wire [2 : 0] sglist_requestAdapter_count_D_IN;
  wire sglist_requestAdapter_count_EN;

  // register sglist_requestAdapter_fbnbuff
  reg [159 : 0] sglist_requestAdapter_fbnbuff;
  wire [159 : 0] sglist_requestAdapter_fbnbuff_D_IN;
  wire sglist_requestAdapter_fbnbuff_EN;

  // ports of submodule idRequest_requestAdapter_fifo
  wire [31 : 0] idRequest_requestAdapter_fifo_D_IN,
		idRequest_requestAdapter_fifo_D_OUT;
  wire idRequest_requestAdapter_fifo_CLR,
       idRequest_requestAdapter_fifo_DEQ,
       idRequest_requestAdapter_fifo_EMPTY_N,
       idRequest_requestAdapter_fifo_ENQ,
       idRequest_requestAdapter_fifo_FULL_N;

  // ports of submodule idReturn_requestAdapter_fifo
  wire [31 : 0] idReturn_requestAdapter_fifo_D_IN,
		idReturn_requestAdapter_fifo_D_OUT;
  wire idReturn_requestAdapter_fifo_CLR,
       idReturn_requestAdapter_fifo_DEQ,
       idReturn_requestAdapter_fifo_EMPTY_N,
       idReturn_requestAdapter_fifo_ENQ,
       idReturn_requestAdapter_fifo_FULL_N;

  // ports of submodule region_requestAdapter_fifo
  wire [415 : 0] region_requestAdapter_fifo_D_IN,
		 region_requestAdapter_fifo_D_OUT;
  wire region_requestAdapter_fifo_CLR,
       region_requestAdapter_fifo_DEQ,
       region_requestAdapter_fifo_EMPTY_N,
       region_requestAdapter_fifo_ENQ,
       region_requestAdapter_fifo_FULL_N;

  // ports of submodule setInterface_requestAdapter_fifo
  wire [63 : 0] setInterface_requestAdapter_fifo_D_IN,
		setInterface_requestAdapter_fifo_D_OUT;
  wire setInterface_requestAdapter_fifo_CLR,
       setInterface_requestAdapter_fifo_DEQ,
       setInterface_requestAdapter_fifo_EMPTY_N,
       setInterface_requestAdapter_fifo_ENQ,
       setInterface_requestAdapter_fifo_FULL_N;

  // ports of submodule sglist_requestAdapter_fifo
  wire [159 : 0] sglist_requestAdapter_fifo_D_IN,
		 sglist_requestAdapter_fifo_D_OUT;
  wire sglist_requestAdapter_fifo_CLR,
       sglist_requestAdapter_fifo_DEQ,
       sglist_requestAdapter_fifo_EMPTY_N,
       sglist_requestAdapter_fifo_ENQ,
       sglist_requestAdapter_fifo_FULL_N;

  // remaining internal signals
  wire [3 : 0] x__h1379;
  wire [2 : 0] x__h1251;
  wire x__h1701;

  // value method portalIfc_messageSize_size
  always@(portalIfc_messageSize_size_methodNumber)
  begin
    case (portalIfc_messageSize_size_methodNumber)
      16'd0: portalIfc_messageSize_size = 16'd160;
      16'd1: portalIfc_messageSize_size = 16'd416;
      16'd2, 16'd3: portalIfc_messageSize_size = 16'd32;
      default: portalIfc_messageSize_size = 16'd64;
    endcase
  end
  assign RDY_portalIfc_messageSize_size = 1'd1 ;

  // action method portalIfc_requests_0_enq
  assign RDY_portalIfc_requests_0_enq =
	     sglist_requestAdapter_count < 3'd4 ||
	     sglist_requestAdapter_fifo_FULL_N ;

  // value method portalIfc_requests_0_notFull
  assign portalIfc_requests_0_notFull = sglist_requestAdapter_fifo_FULL_N ;
  assign RDY_portalIfc_requests_0_notFull = 1'd1 ;

  // action method portalIfc_requests_1_enq
  assign RDY_portalIfc_requests_1_enq =
	     region_requestAdapter_count < 4'd12 ||
	     region_requestAdapter_fifo_FULL_N ;

  // value method portalIfc_requests_1_notFull
  assign portalIfc_requests_1_notFull = region_requestAdapter_fifo_FULL_N ;
  assign RDY_portalIfc_requests_1_notFull = 1'd1 ;

  // action method portalIfc_requests_2_enq
  assign RDY_portalIfc_requests_2_enq = idRequest_requestAdapter_fifo_FULL_N ;

  // value method portalIfc_requests_2_notFull
  assign portalIfc_requests_2_notFull = idRequest_requestAdapter_fifo_FULL_N ;
  assign RDY_portalIfc_requests_2_notFull = 1'd1 ;

  // action method portalIfc_requests_3_enq
  assign RDY_portalIfc_requests_3_enq = idReturn_requestAdapter_fifo_FULL_N ;

  // value method portalIfc_requests_3_notFull
  assign portalIfc_requests_3_notFull = idReturn_requestAdapter_fifo_FULL_N ;
  assign RDY_portalIfc_requests_3_notFull = 1'd1 ;

  // action method portalIfc_requests_4_enq
  assign RDY_portalIfc_requests_4_enq =
	     !setInterface_requestAdapter_count ||
	     setInterface_requestAdapter_fifo_FULL_N ;

  // value method portalIfc_requests_4_notFull
  assign portalIfc_requests_4_notFull =
	     setInterface_requestAdapter_fifo_FULL_N ;
  assign RDY_portalIfc_requests_4_notFull = 1'd1 ;

  // value method portalIfc_intr_status
  assign portalIfc_intr_status = 1'd0 ;
  assign RDY_portalIfc_intr_status = 1'd1 ;

  // value method portalIfc_intr_channel
  assign portalIfc_intr_channel = 32'hFFFFFFFF ;
  assign RDY_portalIfc_intr_channel = 1'd1 ;

  // value method pipes_sglist_PipeOut_first
  assign pipes_sglist_PipeOut_first = sglist_requestAdapter_fifo_D_OUT ;
  assign RDY_pipes_sglist_PipeOut_first = sglist_requestAdapter_fifo_EMPTY_N ;

  // action method pipes_sglist_PipeOut_deq
  assign RDY_pipes_sglist_PipeOut_deq = sglist_requestAdapter_fifo_EMPTY_N ;

  // value method pipes_sglist_PipeOut_notEmpty
  assign pipes_sglist_PipeOut_notEmpty = sglist_requestAdapter_fifo_EMPTY_N ;
  assign RDY_pipes_sglist_PipeOut_notEmpty = 1'd1 ;

  // value method pipes_region_PipeOut_first
  assign pipes_region_PipeOut_first = region_requestAdapter_fifo_D_OUT ;
  assign RDY_pipes_region_PipeOut_first = region_requestAdapter_fifo_EMPTY_N ;

  // action method pipes_region_PipeOut_deq
  assign RDY_pipes_region_PipeOut_deq = region_requestAdapter_fifo_EMPTY_N ;

  // value method pipes_region_PipeOut_notEmpty
  assign pipes_region_PipeOut_notEmpty = region_requestAdapter_fifo_EMPTY_N ;
  assign RDY_pipes_region_PipeOut_notEmpty = 1'd1 ;

  // value method pipes_idRequest_PipeOut_first
  assign pipes_idRequest_PipeOut_first = idRequest_requestAdapter_fifo_D_OUT ;
  assign RDY_pipes_idRequest_PipeOut_first =
	     idRequest_requestAdapter_fifo_EMPTY_N ;

  // action method pipes_idRequest_PipeOut_deq
  assign RDY_pipes_idRequest_PipeOut_deq =
	     idRequest_requestAdapter_fifo_EMPTY_N ;

  // value method pipes_idRequest_PipeOut_notEmpty
  assign pipes_idRequest_PipeOut_notEmpty =
	     idRequest_requestAdapter_fifo_EMPTY_N ;
  assign RDY_pipes_idRequest_PipeOut_notEmpty = 1'd1 ;

  // value method pipes_idReturn_PipeOut_first
  assign pipes_idReturn_PipeOut_first = idReturn_requestAdapter_fifo_D_OUT ;
  assign RDY_pipes_idReturn_PipeOut_first =
	     idReturn_requestAdapter_fifo_EMPTY_N ;

  // action method pipes_idReturn_PipeOut_deq
  assign RDY_pipes_idReturn_PipeOut_deq =
	     idReturn_requestAdapter_fifo_EMPTY_N ;

  // value method pipes_idReturn_PipeOut_notEmpty
  assign pipes_idReturn_PipeOut_notEmpty =
	     idReturn_requestAdapter_fifo_EMPTY_N ;
  assign RDY_pipes_idReturn_PipeOut_notEmpty = 1'd1 ;

  // value method pipes_setInterface_PipeOut_first
  assign pipes_setInterface_PipeOut_first =
	     setInterface_requestAdapter_fifo_D_OUT ;
  assign RDY_pipes_setInterface_PipeOut_first =
	     setInterface_requestAdapter_fifo_EMPTY_N ;

  // action method pipes_setInterface_PipeOut_deq
  assign RDY_pipes_setInterface_PipeOut_deq =
	     setInterface_requestAdapter_fifo_EMPTY_N ;

  // value method pipes_setInterface_PipeOut_notEmpty
  assign pipes_setInterface_PipeOut_notEmpty =
	     setInterface_requestAdapter_fifo_EMPTY_N ;
  assign RDY_pipes_setInterface_PipeOut_notEmpty = 1'd1 ;

  // submodule idRequest_requestAdapter_fifo
  FIFO1 #(.width(32'd32),
	  .guarded(1'd1)) idRequest_requestAdapter_fifo(.RST(RST_N),
							.CLK(CLK),
							.D_IN(idRequest_requestAdapter_fifo_D_IN),
							.ENQ(idRequest_requestAdapter_fifo_ENQ),
							.DEQ(idRequest_requestAdapter_fifo_DEQ),
							.CLR(idRequest_requestAdapter_fifo_CLR),
							.D_OUT(idRequest_requestAdapter_fifo_D_OUT),
							.FULL_N(idRequest_requestAdapter_fifo_FULL_N),
							.EMPTY_N(idRequest_requestAdapter_fifo_EMPTY_N));

  // submodule idReturn_requestAdapter_fifo
  FIFO1 #(.width(32'd32),
	  .guarded(1'd1)) idReturn_requestAdapter_fifo(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(idReturn_requestAdapter_fifo_D_IN),
						       .ENQ(idReturn_requestAdapter_fifo_ENQ),
						       .DEQ(idReturn_requestAdapter_fifo_DEQ),
						       .CLR(idReturn_requestAdapter_fifo_CLR),
						       .D_OUT(idReturn_requestAdapter_fifo_D_OUT),
						       .FULL_N(idReturn_requestAdapter_fifo_FULL_N),
						       .EMPTY_N(idReturn_requestAdapter_fifo_EMPTY_N));

  // submodule region_requestAdapter_fifo
  FIFO1 #(.width(32'd416),
	  .guarded(1'd1)) region_requestAdapter_fifo(.RST(RST_N),
						     .CLK(CLK),
						     .D_IN(region_requestAdapter_fifo_D_IN),
						     .ENQ(region_requestAdapter_fifo_ENQ),
						     .DEQ(region_requestAdapter_fifo_DEQ),
						     .CLR(region_requestAdapter_fifo_CLR),
						     .D_OUT(region_requestAdapter_fifo_D_OUT),
						     .FULL_N(region_requestAdapter_fifo_FULL_N),
						     .EMPTY_N(region_requestAdapter_fifo_EMPTY_N));

  // submodule setInterface_requestAdapter_fifo
  FIFO1 #(.width(32'd64),
	  .guarded(1'd1)) setInterface_requestAdapter_fifo(.RST(RST_N),
							   .CLK(CLK),
							   .D_IN(setInterface_requestAdapter_fifo_D_IN),
							   .ENQ(setInterface_requestAdapter_fifo_ENQ),
							   .DEQ(setInterface_requestAdapter_fifo_DEQ),
							   .CLR(setInterface_requestAdapter_fifo_CLR),
							   .D_OUT(setInterface_requestAdapter_fifo_D_OUT),
							   .FULL_N(setInterface_requestAdapter_fifo_FULL_N),
							   .EMPTY_N(setInterface_requestAdapter_fifo_EMPTY_N));

  // submodule sglist_requestAdapter_fifo
  FIFO1 #(.width(32'd160),
	  .guarded(1'd1)) sglist_requestAdapter_fifo(.RST(RST_N),
						     .CLK(CLK),
						     .D_IN(sglist_requestAdapter_fifo_D_IN),
						     .ENQ(sglist_requestAdapter_fifo_ENQ),
						     .DEQ(sglist_requestAdapter_fifo_DEQ),
						     .CLR(sglist_requestAdapter_fifo_CLR),
						     .D_OUT(sglist_requestAdapter_fifo_D_OUT),
						     .FULL_N(sglist_requestAdapter_fifo_FULL_N),
						     .EMPTY_N(sglist_requestAdapter_fifo_EMPTY_N));

  // register idRequest_requestAdapter_fbnbuff
  assign idRequest_requestAdapter_fbnbuff_D_IN = portalIfc_requests_2_enq_v ;
  assign idRequest_requestAdapter_fbnbuff_EN = EN_portalIfc_requests_2_enq ;

  // register idReturn_requestAdapter_fbnbuff
  assign idReturn_requestAdapter_fbnbuff_D_IN = portalIfc_requests_3_enq_v ;
  assign idReturn_requestAdapter_fbnbuff_EN = EN_portalIfc_requests_3_enq ;

  // register region_requestAdapter_count
  assign region_requestAdapter_count_D_IN =
	     (region_requestAdapter_count == 4'd12) ? 4'd0 : x__h1379 ;
  assign region_requestAdapter_count_EN = EN_portalIfc_requests_1_enq ;

  // register region_requestAdapter_fbnbuff
  assign region_requestAdapter_fbnbuff_D_IN =
	     { region_requestAdapter_fbnbuff[383:0],
	       portalIfc_requests_1_enq_v } ;
  assign region_requestAdapter_fbnbuff_EN = EN_portalIfc_requests_1_enq ;

  // register setInterface_requestAdapter_count
  assign setInterface_requestAdapter_count_D_IN =
	     !setInterface_requestAdapter_count && x__h1701 ;
  assign setInterface_requestAdapter_count_EN = EN_portalIfc_requests_4_enq ;

  // register setInterface_requestAdapter_fbnbuff
  assign setInterface_requestAdapter_fbnbuff_D_IN =
	     { setInterface_requestAdapter_fbnbuff[31:0],
	       portalIfc_requests_4_enq_v } ;
  assign setInterface_requestAdapter_fbnbuff_EN =
	     EN_portalIfc_requests_4_enq ;

  // register sglist_requestAdapter_count
  assign sglist_requestAdapter_count_D_IN =
	     (sglist_requestAdapter_count == 3'd4) ? 3'd0 : x__h1251 ;
  assign sglist_requestAdapter_count_EN = EN_portalIfc_requests_0_enq ;

  // register sglist_requestAdapter_fbnbuff
  assign sglist_requestAdapter_fbnbuff_D_IN =
	     { sglist_requestAdapter_fbnbuff[127:0],
	       portalIfc_requests_0_enq_v } ;
  assign sglist_requestAdapter_fbnbuff_EN = EN_portalIfc_requests_0_enq ;

  // submodule idRequest_requestAdapter_fifo
  assign idRequest_requestAdapter_fifo_D_IN = portalIfc_requests_2_enq_v ;
  assign idRequest_requestAdapter_fifo_ENQ = EN_portalIfc_requests_2_enq ;
  assign idRequest_requestAdapter_fifo_DEQ = EN_pipes_idRequest_PipeOut_deq ;
  assign idRequest_requestAdapter_fifo_CLR = 1'b0 ;

  // submodule idReturn_requestAdapter_fifo
  assign idReturn_requestAdapter_fifo_D_IN = portalIfc_requests_3_enq_v ;
  assign idReturn_requestAdapter_fifo_ENQ = EN_portalIfc_requests_3_enq ;
  assign idReturn_requestAdapter_fifo_DEQ = EN_pipes_idReturn_PipeOut_deq ;
  assign idReturn_requestAdapter_fifo_CLR = 1'b0 ;

  // submodule region_requestAdapter_fifo
  assign region_requestAdapter_fifo_D_IN =
	     { region_requestAdapter_fbnbuff[383:0],
	       portalIfc_requests_1_enq_v } ;
  assign region_requestAdapter_fifo_ENQ =
	     EN_portalIfc_requests_1_enq &&
	     region_requestAdapter_count == 4'd12 ;
  assign region_requestAdapter_fifo_DEQ = EN_pipes_region_PipeOut_deq ;
  assign region_requestAdapter_fifo_CLR = 1'b0 ;

  // submodule setInterface_requestAdapter_fifo
  assign setInterface_requestAdapter_fifo_D_IN =
	     { setInterface_requestAdapter_fbnbuff[31:0],
	       portalIfc_requests_4_enq_v } ;
  assign setInterface_requestAdapter_fifo_ENQ =
	     EN_portalIfc_requests_4_enq &&
	     setInterface_requestAdapter_count ;
  assign setInterface_requestAdapter_fifo_DEQ =
	     EN_pipes_setInterface_PipeOut_deq ;
  assign setInterface_requestAdapter_fifo_CLR = 1'b0 ;

  // submodule sglist_requestAdapter_fifo
  assign sglist_requestAdapter_fifo_D_IN =
	     { sglist_requestAdapter_fbnbuff[127:0],
	       portalIfc_requests_0_enq_v } ;
  assign sglist_requestAdapter_fifo_ENQ =
	     EN_portalIfc_requests_0_enq &&
	     sglist_requestAdapter_count == 3'd4 ;
  assign sglist_requestAdapter_fifo_DEQ = EN_pipes_sglist_PipeOut_deq ;
  assign sglist_requestAdapter_fifo_CLR = 1'b0 ;

  // remaining internal signals
  assign x__h1251 = sglist_requestAdapter_count + 3'd1 ;
  assign x__h1379 = region_requestAdapter_count + 4'd1 ;
  assign x__h1701 = setInterface_requestAdapter_count + 1'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        idRequest_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY 32'd0;
	idReturn_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY 32'd0;
	region_requestAdapter_count <= `BSV_ASSIGNMENT_DELAY 4'd0;
	region_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY 416'd0;
	setInterface_requestAdapter_count <= `BSV_ASSIGNMENT_DELAY 1'd0;
	setInterface_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY 64'd0;
	sglist_requestAdapter_count <= `BSV_ASSIGNMENT_DELAY 3'd0;
	sglist_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY 160'd0;
      end
    else
      begin
        if (idRequest_requestAdapter_fbnbuff_EN)
	  idRequest_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY
	      idRequest_requestAdapter_fbnbuff_D_IN;
	if (idReturn_requestAdapter_fbnbuff_EN)
	  idReturn_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY
	      idReturn_requestAdapter_fbnbuff_D_IN;
	if (region_requestAdapter_count_EN)
	  region_requestAdapter_count <= `BSV_ASSIGNMENT_DELAY
	      region_requestAdapter_count_D_IN;
	if (region_requestAdapter_fbnbuff_EN)
	  region_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY
	      region_requestAdapter_fbnbuff_D_IN;
	if (setInterface_requestAdapter_count_EN)
	  setInterface_requestAdapter_count <= `BSV_ASSIGNMENT_DELAY
	      setInterface_requestAdapter_count_D_IN;
	if (setInterface_requestAdapter_fbnbuff_EN)
	  setInterface_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY
	      setInterface_requestAdapter_fbnbuff_D_IN;
	if (sglist_requestAdapter_count_EN)
	  sglist_requestAdapter_count <= `BSV_ASSIGNMENT_DELAY
	      sglist_requestAdapter_count_D_IN;
	if (sglist_requestAdapter_fbnbuff_EN)
	  sglist_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY
	      sglist_requestAdapter_fbnbuff_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    idRequest_requestAdapter_fbnbuff = 32'hAAAAAAAA;
    idReturn_requestAdapter_fbnbuff = 32'hAAAAAAAA;
    region_requestAdapter_count = 4'hA;
    region_requestAdapter_fbnbuff =
	416'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    setInterface_requestAdapter_count = 1'h0;
    setInterface_requestAdapter_fbnbuff = 64'hAAAAAAAAAAAAAAAA;
    sglist_requestAdapter_count = 3'h2;
    sglist_requestAdapter_fbnbuff =
	160'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkMMURequestInput

